#!/usr/bin/env python3
"""De rollenspellen van C5 «Español en la práctica».

Eén scène per unidad, gebouwd op de woordenschat van díe unidad
(`01-cursussen/05-a1/U<n>/u<n>_vocab.json`) en op wat er grammaticaal aan bod
is. De vorm staat beschreven in de kop van `rol_data.py`; hier staat alleen de
inhoud.

DE SCÈNE VOLGT DE PARADA
De reis van C5 loopt van España naar México, Colombia en Perú (CLAUDE.md §12),
en de tegenspeler hoort thuis waar de unit zich afspeelt: een conciërge in
Madrid, een verkoopster op een tianguis in Mexico-Stad, een buurvrouw in
Cartagena. Zo is het rollenspel geen losse oefening maar dezelfde reis.

NIET ELKE UNIT IS EEN WINKEL
Een transactie (bestellen, kopen, de weg vragen) is het makkelijkst te sluiten,
maar niet elke unidad gaat daarover. Waar het thema dat niet toelaat, is de
scène een gesprek met een dóél: een fiche invullen, een foto uitleggen, een
afspraak maken, vertellen wat je gedaan hebt. Het punt is niet de toonbank maar
dat het gesprek ergens naartoe loopt en ophoudt.
"""

ROLES = {
 # ── U0 · ¡Empezamos! · el mundo hispano → España ──────────────────────────
 0: {
  "titulo": "El primer día",
  "lugar": "Madrid · la secretaría del instituto",
  "tu": "Tú, de nieuwe leerling",
  "otro": "La secretaria",
  "otro_avatar": "🗂️",
  "mision": "Meld je aan op je eerste schooldag: groet, zeg hoe je heet, spel "
            "je naam, zeg hoe oud je bent en waar je vandaan komt.",
  "mision_es": "Preséntate en la secretaría: nombre, edad y país.",
  "pasos": [
   {"di": "¡Buenos días! ¿Qué tal? Yo soy Marta, la secretaria. ¿Cómo te llamas?",
    "nl": "Goedemorgen! Hoe gaat het? Ik ben Marta, de secretaresse. Hoe heet jij?",
    "meta": "Groet terug en zeg hoe je heet.",
    "hueco": {"marco": "Buenos días. ___ ___ Lars.",
              "respuestas": [["me"], ["llamo"]],
              "banco": ["me", "yo", "llamo", "llamas", "soy"],
              "mal": ["Het werkwoord is wederkerend: <b>me</b> llamo, letterlijk «ik noem mij».",
                      "Bij <i>yo</i> hoort <b>llamo</b>. <i>Llamas</i> is de jij-vorm."]},
    "opciones": [
      ("Buenos días. Me llamo Lars.", True, None),
      ("Buenos días. Yo llamo Lars.", False,
       "<b>Me llamo</b> — zonder <i>me</i> betekent het «ik bel»."),
    ],
    "acepta": [r"me\s+llamo\s+\w+", r"(yo\s+)?soy\s+\w+"],
    "pista": "Twee mogelijkheden: «Me llamo …» of «Soy …».",
    "modelo": "Buenos días. Me llamo Lars."},

   {"di": "Mucho gusto, Lars. ¿Puedes deletrear tu apellido, por favor?",
    "nl": "Aangenaam, Lars. Kan je je achternaam spellen, alsjeblieft?",
    "meta": "Spel je achternaam. In het Spaans heet de w «uve doble» en de j «jota».",
    "hueco": {"marco": "Sí, claro: ___, a, ene, ___, e, ene.",
              "respuestas": [["uve doble", "uvedoble", "doble uve", "w"], ["ese", "s"]],
              "banco": ["uve doble", "jota", "hache", "ese", "ce"],
              "mal": ["De <b>w</b> heet in het Spaans <i>uve doble</i>.",
                      "De <b>s</b> heet <i>ese</i> — schrijf de letter of haar naam."]},
    "opciones": [
      ("Sí, claro: uve doble, a, ene, ese, e, ene.", True, None),
      ("Sí, claro: we, a, en, es, e, en.", False,
       "Dat zijn de Nederlandse lettergrepen. In het Spaans: <b>uve doble · a · "
       "ene · ese · e · ene</b>."),
    ],
    "acepta": [r"(uve\s*doble|doble\s*uve|w)", r"\b(ese|s)\b"],
    "pista": "De letters die je nodig hebt: uve doble · a · ene · ese · e · ene.",
    "modelo": "Sí, claro: uve doble, a, ene, ese, e, ene."},

   {"di": "Gracias. ¿Y cuántos años tienes?",
    "nl": "Dank je. En hoe oud ben je?",
    "meta": "Zeg hoe oud je bent. Let op: in het Spaans «heb» je jaren.",
    "hueco": {"marco": "___ dieciséis ___.",
              "respuestas": [["tengo"], ["años", "anos"]],
              "banco": ["tengo", "soy", "años", "año", "edad"],
              "mal": ["Leeftijd krijgt <b>tener</b>: je «hébt» zestien jaar.",
                      "Meervoud: <b>años</b>, met ñ."]},
    "opciones": [
      ("Tengo dieciséis años.", True, None),
      ("Soy dieciséis años.", False,
       "Met <i>ser</i> zeg je wát je bent. Leeftijd gaat met <b>tener</b>: "
       "«tengo dieciséis años»."),
    ],
    "acepta": [r"tengo\s+\w+\s*a[ñn]os"],
    "pista": "Begin met «Tengo…» en eindig met «…años».",
    "modelo": "Tengo dieciséis años."},

   {"di": "Muy bien. ¿Y de dónde eres?",
    "nl": "Heel goed. En waar kom je vandaan?",
    "meta": "Zeg uit welk land je komt.",
    "hueco": {"marco": "___ ___ Bélgica.",
              "respuestas": [["soy"], ["de"]],
              "banco": ["soy", "estoy", "de", "en", "a"],
              "mal": ["Waar je vandaan komt, zeg je met <b>ser</b>: «soy de…».",
                      "Herkomst krijgt <b>de</b>: soy <i>de</i> Bélgica."]},
    "opciones": [
      ("Soy de Bélgica.", True, None),
      ("Soy en Bélgica.", False,
       "«Soy de» = ik kom uit. «Estoy en» = ik ben (nu) in."),
      ("Estoy de Bélgica.", False,
       "Herkomst gaat met <b>ser</b>, niet met <i>estar</i>: «soy de Bélgica»."),
    ],
    "acepta": [r"soy\s+de\s+\w+", r"soy\s+belga"],
    "pista": "«Soy de …» + je land. Of in één woord: «Soy belga».",
    "modelo": "Soy de Bélgica."},

   {"di": "Perfecto. Aquí tienes tu horario. ¿Alguna pregunta?",
    "nl": "Perfect. Hier is je uurrooster. Nog een vraag?",
    "meta": "Je verstond één woord niet. Vraag wat het betekent.",
    "hueco": {"marco": "Perdona, ¿qué ___ «horario»? No ___.",
              "respuestas": [["significa"], ["entiendo"]],
              "banco": ["significa", "dice", "entiendo", "entiendes", "repites"],
              "mal": ["«Wat betekent…?» is <b>¿qué significa…?</b>",
                      "Bij <i>yo</i>: <b>entiendo</b>. <i>Entiendes</i> is de jij-vorm."]},
    "opciones": [
      ("Perdona, ¿qué significa «horario»? No entiendo.", True, None),
      ("Perdona, ¿cómo se dice «horario»? No entiendo.", False,
       "<b>¿Cómo se dice…?</b> vraag je als je het Spaanse wóórd zoekt. Wil je "
       "de betekenis weten, dan is het <b>¿qué significa…?</b>"),
    ],
    "acepta": [r"qu[eé]\s+significa", r"no\s+entiendo", r"puedes\s+repetir"],
    "pista": "Drie klasuitdrukkingen: ¿qué significa…? · no entiendo · "
             "¿puedes repetir?",
    "modelo": "Perdona, ¿qué significa «horario»? No entiendo."},
  ],
  "final": "Claro: es la lista de tus clases. ¡Bienvenido y mucha suerte!",
  "final_nl": "Natuurlijk: dat is de lijst van je lessen. Welkom en veel succes!",
 },

 # ── U1 · ¿Quién eres? · Madrid ────────────────────────────────────────────
 1: {
  "titulo": "La ficha del club",
  "lugar": "Madrid · el club de baloncesto del barrio",
  "tu": "Tú, die lid wil worden",
  "otro": "El monitor",
  "otro_avatar": "🏀",
  "mision": "Word lid van de club: geef je naam, leeftijd, waar je woont en je "
            "nationaliteit, en vraag zelf iets terug.",
  "mision_es": "Rellena la ficha del club: nombre, edad, dónde vives, nacionalidad.",
  "pasos": [
   {"di": "¡Hola! ¿Quieres apuntarte? Necesito rellenar tu ficha. ¿Cuál es tu nombre completo?",
    "nl": "Hallo! Wil je je inschrijven? Ik moet je fiche invullen. Wat is je volledige naam?",
    "meta": "Geef je voornaam én je achternaam.",
    "hueco": {"marco": "Mi ___ es Lars y mi ___ es Wansen.",
              "respuestas": [["nombre"], ["apellido"]],
              "banco": ["nombre", "apellido", "edad", "firma", "curso"],
              "mal": ["Je voornaam is <b>el nombre</b>.",
                      "Je achternaam is <b>el apellido</b> — niet te verwarren met <i>nombre</i>."]},
    "opciones": [
      ("Mi nombre es Lars y mi apellido es Wansen.", True, None),
      ("Mi apellido es Lars y mi nombre es Wansen.", False,
       "Omgekeerd: <b>nombre</b> is je voornaam, <b>apellido</b> je achternaam."),
    ],
    "acepta": [r"(mi\s+)?nombre\s+es\s+\w+", r"me\s+llamo\s+\w+"],
    "pista": "«Mi nombre es …» en «mi apellido es …».",
    "modelo": "Mi nombre es Lars y mi apellido es Wansen."},

   {"di": "Vale. ¿Y dónde vives exactamente?",
    "nl": "Oké. En waar woon je precies?",
    "meta": "Zeg in welke stad je woont.",
    "hueco": {"marco": "___ ___ Gante, en Bélgica.",
              "respuestas": [["vivo"], ["en"]],
              "banco": ["vivo", "soy", "en", "de", "a"],
              "mal": ["Wonen is <b>vivir</b>: bij <i>yo</i> wordt dat <b>vivo</b>.",
                      "Waar je woont krijgt <b>en</b>. <i>De</i> gebruik je voor je herkomst."]},
    "opciones": [
      ("Vivo en Gante, en Bélgica.", True, None),
      ("Vivo de Gante, en Bélgica.", False,
       "<b>Vivo en</b> — met <i>de</i> zeg je waar je vandaan komt, niet waar je woont."),
      ("Soy en Gante, en Bélgica.", False,
       "«Ik woon» is <b>vivo</b>. «Soy» zou «ik ben» zijn."),
    ],
    "acepta": [r"vivo\s+en\s+\w+"],
    "pista": "«Vivo en …» + je stad.",
    "modelo": "Vivo en Gante, en Bélgica."},

   {"di": "¿Y qué nacionalidad tienes?",
    "nl": "En welke nationaliteit heb je?",
    "meta": "Zeg je nationaliteit. Let op: die schrijf je zonder hoofdletter.",
    "hueco": {"marco": "___ ___.",
              "respuestas": [["soy"], ["belga"]],
              "banco": ["soy", "tengo", "belga", "Bélgica", "belgo"],
              "mal": ["Nationaliteit gaat met <b>ser</b>: «soy belga».",
                      "Het woord is <b>belga</b> — hetzelfde voor jongens en meisjes, "
                      "en met kleine letter."]},
    "opciones": [
      ("Soy belga.", True, None),
      ("Soy Bélgica.", False,
       "<b>Bélgica</b> is het land, <b>belga</b> is de nationaliteit."),
      ("Tengo belga.", False,
       "Nationaliteit gaat met <b>ser</b>, niet met <i>tener</i>."),
    ],
    "acepta": [r"soy\s+belga", r"soy\s+de\s+b[eé]lgica"],
    "pista": "Eén woord volstaat na «soy»: belga.",
    "modelo": "Soy belga."},

   {"di": "Perfecto. Los entrenamientos son los martes y los jueves. ¿Alguna pregunta para mí?",
    "nl": "Perfect. De trainingen zijn op dinsdag en donderdag. Nog een vraag voor mij?",
    "meta": "Vraag hém iets terug: hoe hij heet.",
    "hueco": {"marco": "Sí: ¿___ te ___?",
              "respuestas": [["cómo", "como"], ["llamas"]],
              "banco": ["cómo", "qué", "llamas", "llamo", "llama"],
              "mal": ["«Hoe» is <b>cómo</b>, met accent in een vraag.",
                      "Je vraagt het aan hém: <b>te llamas</b>."]},
    "opciones": [
      ("Sí: ¿cómo te llamas?", True, None),
      ("Sí: ¿cómo me llamo?", False,
       "Dan vraag je hoe jíj heet. Aan hem is het <b>¿cómo te llamas?</b>"),
    ],
    "acepta": [r"c[oó]mo\s+te\s+llamas", r"y\s+t[uú]"],
    "pista": "De vraag die je in de eerste les leerde: ¿Cómo te …?",
    "modelo": "Sí: ¿cómo te llamas?"},

   {"di": "Me llamo Sergio. ¡Bienvenido al equipo!",
    "nl": "Ik heet Sergio. Welkom bij het team!",
    "meta": "Reageer beleefd op de kennismaking.",
    "hueco": {"marco": "___, Sergio. ___ gusto.",
              "respuestas": [["encantado", "encantada"], ["mucho"]],
              "banco": ["encantado", "adiós", "mucho", "muy", "gracias"],
              "mal": ["Bij een kennismaking zeg je <b>encantado</b> (jongen) of "
                      "<b>encantada</b> (meisje).",
                      "De vaste uitdrukking is <b>mucho gusto</b>, niet «muy gusto»."]},
    "opciones": [
      ("Encantado, Sergio. Mucho gusto.", True, None),
      ("Encantado, Sergio. Muy gusto.", False,
       "Het is <b>mucho gusto</b>. <i>Muy</i> staat alleen bij een bijvoeglijk "
       "naamwoord: «muy bien»."),
    ],
    "acepta": [r"encantad[oa]", r"mucho\s+gusto", r"igualmente"],
    "pista": "Drie mogelijkheden: encantado/a · mucho gusto · igualmente.",
    "modelo": "Encantado, Sergio. Mucho gusto."},
  ],
  "final": "¡Nos vemos el martes a las seis! Hasta luego.",
  "final_nl": "Tot dinsdag om zes uur! Tot ziens.",
 },

 # ── U2 · Mi gente · Andalucía (Sevilla) ───────────────────────────────────
 2: {
  "titulo": "La foto de familia",
  "lugar": "Sevilla · en casa de Lucía",
  "tu": "Tú, op bezoek",
  "otro": "Lucía",
  "otro_avatar": "🌺",
  "mision": "Lucía toont je een foto van haar familie en vraagt daarna naar de "
            "jouwe. Beschrijf wie er op staat en hoe ze zijn.",
  "mision_es": "Habla de tu familia: quién es quién y cómo es cada uno.",
  "pasos": [
   {"di": "Mira, esta es mi familia. Este es mi padre y esta es mi madre. ¿Tienes hermanos?",
    "nl": "Kijk, dit is mijn familie. Dit is mijn vader en dit is mijn moeder. Heb jij broers of zussen?",
    "meta": "Zeg hoeveel broers of zussen je hebt.",
    "hueco": {"marco": "Sí, ___ una ___ y un hermano.",
              "respuestas": [["tengo"], ["hermana"]],
              "banco": ["tengo", "soy", "hermana", "hermano", "prima"],
              "mal": ["Bezit gaat met <b>tener</b>: «tengo…».",
                      "Een zus is <b>la hermana</b> — met -a."]},
    "opciones": [
      ("Sí, tengo una hermana y un hermano.", True, None),
      ("Sí, tengo una hermano y un hermana.", False,
       "De lidwoorden staan omgewisseld: <b>una hermana</b>, <b>un hermano</b>."),
    ],
    "acepta": [r"tengo\s+(un|una|dos|tres)\s+herman", r"no\s+tengo\s+herman",
               r"soy\s+hij[oa]\s+[uú]nic[oa]"],
    "pista": "«Tengo un hermano / una hermana». Geen? Dan: «Soy hijo/hija único/a».",
    "modelo": "Sí, tengo una hermana y un hermano."},

   {"di": "¡Qué bien! ¿Y cómo es tu hermana? ¿Se parece a ti?",
    "nl": "Wat leuk! En hoe is je zus? Lijkt ze op jou?",
    "meta": "Beschrijf haar uiterlijk: lengte en haar.",
    "hueco": {"marco": "Es ___ y tiene el pelo ___.",
              "respuestas": [["alta"], ["rubio"]],
              "banco": ["alta", "alto", "rubio", "rubia", "largo"],
              "mal": ["Ze is een meisje: het bijvoeglijk naamwoord wordt <b>alta</b>.",
                      "Het gaat over <i>el pelo</i> — mannelijk — dus <b>rubio</b>, "
                      "ook al is zíj een meisje."]},
    "opciones": [
      ("Es alta y tiene el pelo rubio.", True, None),
      ("Es alto y tiene el pelo rubia.", False,
       "Twee keer mis: <b>alta</b> hoort bij háár, maar <b>rubio</b> hoort bij "
       "<i>el pelo</i>, dat mannelijk is."),
      ("Es alta y tiene el pelo rubia.", False,
       "Bijna. <i>El pelo</i> is mannelijk, dus <b>el pelo rubio</b> — ook bij een meisje."),
    ],
    "acepta": [r"es\s+(alta|baja|delgada|morena|rubia|guapa)",
               r"tiene\s+el\s+pelo\s+\w+"],
    "pista": "Twee bouwstenen: «Es + hoe ze is» en «Tiene el pelo + kleur/lengte».",
    "modelo": "Es alta y tiene el pelo rubio."},

   {"di": "¿Y de carácter? ¿Cómo es?",
    "nl": "En qua karakter? Hoe is ze?",
    "meta": "Beschrijf haar karakter met twee eigenschappen.",
    "hueco": {"marco": "Es muy ___ ___ un poco tímida.",
              "respuestas": [["simpática", "simpatica"], ["pero"]],
              "banco": ["simpática", "simpático", "pero", "y", "también"],
              "mal": ["Over een meisje: <b>simpática</b>.",
                      "Twee dingen die botsen verbind je met <b>pero</b> («maar»)."]},
    "opciones": [
      ("Es muy simpática pero un poco tímida.", True, None),
      ("Es muy simpático pero un poco tímido.", False,
       "Ze is een meisje: <b>simpática</b> en <b>tímida</b>."),
    ],
    "acepta": [r"es\s+(muy\s+)?(simp[aá]tica|maja|graciosa|trabajadora|inteligente|habladora|tranquila|t[ií]mida)"],
    "pista": "Kies uit: simpática · maja · graciosa · trabajadora · inteligente · "
             "tímida. Zet er «muy» of «un poco» voor.",
    "modelo": "Es muy simpática pero un poco tímida."},

   {"di": "Se parece a mi prima. ¿Y tus abuelos? ¿Viven cerca?",
    "nl": "Ze lijkt op mijn nicht. En je grootouders? Wonen die dichtbij?",
    "meta": "Vertel iets over je grootouders.",
    "hueco": {"marco": "Mi ___ vive cerca, pero mis ___ viven lejos.",
              "respuestas": [["abuela"], ["abuelos"]],
              "banco": ["abuela", "abuelo", "abuelos", "padres", "tíos"],
              "mal": ["Eén oma is <b>la abuela</b>.",
                      "Bij <i>mis</i> hoort een meervoud: <b>abuelos</b>."]},
    "opciones": [
      ("Mi abuela vive cerca, pero mis abuelos viven lejos.", True, None),
      ("Mi abuela vive cerca, pero mis abuelo viven lejos.", False,
       "Na <i>mis</i> komt een meervoud: <b>mis abuelos</b>."),
    ],
    "acepta": [r"mi[s]?\s+abuel[oa]s?\s+viv", r"viven?\s+(cerca|lejos)"],
    "pista": "«Mi abuela vive…» (één) of «Mis abuelos viven…» (meer dan één).",
    "modelo": "Mi abuela vive cerca, pero mis abuelos viven lejos."},

   {"di": "En mi familia somos seis. ¿Y en la tuya?",
    "nl": "Bij ons thuis zijn we met zes. En bij jou?",
    "meta": "Zeg met hoeveel jullie thuis zijn.",
    "hueco": {"marco": "En mi familia ___ cuatro: mis padres, mi hermana ___ yo.",
              "respuestas": [["somos"], ["y"]],
              "banco": ["somos", "son", "estamos", "y", "pero"],
              "mal": ["Jij hoort erbij, dus <i>nosotros</i>: <b>somos</b>.",
                      "Een opsomming verbind je met <b>y</b>."]},
    "opciones": [
      ("En mi familia somos cuatro: mis padres, mi hermana y yo.", True, None),
      ("En mi familia son cuatro: mis padres, mi hermana y yo.", False,
       "Jij zit er zelf bij, dus <b>somos</b> (wij zijn), niet <i>son</i>."),
    ],
    "acepta": [r"somos\s+\w+", r"en\s+mi\s+familia"],
    "pista": "«En mi familia somos …» + een getal.",
    "modelo": "En mi familia somos cuatro: mis padres, mi hermana y yo."},
  ],
  "final": "¡Qué familia tan maja! Un día tienes que enseñarme una foto.",
  "final_nl": "Wat een leuke familie! Je moet me eens een foto tonen.",
 },

 # ── U3 · El tiempo vuela · Barcelona ──────────────────────────────────────
 3: {
  "titulo": "¿Quedamos?",
  "lugar": "Barcelona · por mensaje con Pau",
  "tu": "Tú",
  "otro": "Pau",
  "otro_avatar": "⌚",
  "mision": "Maak een afspraak met Pau: zeg hoe laat je kan, waarom het "
            "vroeger niet lukt, en spreek een dag en een uur af.",
  "mision_es": "Queda con Pau: di a qué hora puedes y por qué antes no.",
  "pasos": [
   {"di": "¡Ey! ¿Quieres quedar mañana por la tarde?",
    "nl": "Hey! Wil je morgennamiddag afspreken?",
    "meta": "Zeg ja, maar niet te vroeg — je hebt school tot vier uur.",
    "hueco": {"marco": "¡Vale! Pero ___ ___ hasta las cuatro.",
              "respuestas": [["tengo"], ["clase", "clases"]],
              "banco": ["tengo", "soy", "clase", "hora", "tiempo"],
              "mal": ["«Ik heb les» is <b>tengo clase</b>.",
                      "Het woord dat je zoekt is <b>clase</b> (of <i>clases</i>)."]},
    "opciones": [
      ("¡Vale! Pero tengo clase hasta las cuatro.", True, None),
      ("¡Vale! Pero soy clase hasta las cuatro.", False,
       "«Ik heb les» is <b>tengo clase</b>, met <i>tener</i>."),
    ],
    "acepta": [r"tengo\s+(clase|clases)", r"hasta\s+las?\s+\w+", r"vale|de\s+acuerdo"],
    "pista": "«Vale» om ja te zeggen, en dan «tengo clase hasta las…».",
    "modelo": "¡Vale! Pero tengo clase hasta las cuatro."},

   {"di": "Sin problema. ¿A qué hora quedamos entonces?",
    "nl": "Geen probleem. Hoe laat spreken we dan af?",
    "meta": "Stel half vijf voor.",
    "hueco": {"marco": "¿___ las cuatro ___ media?",
              "respuestas": [["a"], ["y"]],
              "banco": ["a", "en", "y", "menos", "de"],
              "mal": ["Een tijdstip krijgt <b>a</b>: «a las cuatro».",
                      "Half vijf is in het Spaans «vier uur <b>y</b> media»."]},
    "opciones": [
      ("¿A las cuatro y media?", True, None),
      ("¿A las cuatro y medio?", False,
       "Het is <b>y media</b> — het verwijst naar <i>la hora</i>, vrouwelijk."),
      ("¿En las cuatro y media?", False,
       "Een uur krijgt <b>a</b>, niet <i>en</i>: «a las cuatro y media»."),
    ],
    "acepta": [r"a\s+las?\s+\w+", r"y\s+(media|cuarto)", r"menos\s+cuarto"],
    "pista": "«A las …» + het uur. Half = <i>y media</i>, kwart over = <i>y cuarto</i>.",
    "modelo": "¿A las cuatro y media?"},

   {"di": "Perfecto. Oye, ¿tú a qué hora te levantas normalmente?",
    "nl": "Perfect. Zeg, hoe laat sta jij normaal op?",
    "meta": "Vertel over je ochtend: opstaan en douchen.",
    "hueco": {"marco": "___ ___ a las siete y me ducho.",
              "respuestas": [["me"], ["levanto"]],
              "banco": ["me", "yo", "levanto", "levantas", "despierto"],
              "mal": ["Wederkerend werkwoord: <b>me</b> levanto.",
                      "Bij <i>yo</i>: <b>levanto</b>. <i>Levantas</i> is de jij-vorm."]},
    "opciones": [
      ("Me levanto a las siete y me ducho.", True, None),
      ("Yo levanto a las siete y ducho.", False,
       "Allebei wederkerend: <b>me levanto</b> en <b>me ducho</b>."),
    ],
    "acepta": [r"me\s+(levanto|despierto)", r"a\s+las?\s+\w+"],
    "pista": "«Me levanto a las …». Vergeet het kleine woordje <i>me</i> niet.",
    "modelo": "Me levanto a las siete y me ducho."},

   {"di": "¡Qué pronto! Yo prefiero dormir. ¿Y los fines de semana?",
    "nl": "Wat vroeg! Ik slaap liever uit. En in het weekend?",
    "meta": "Zeg hoe vaak je uitslaapt. Gebruik een woord voor «hoe vaak».",
    "hueco": {"marco": "Los fines de semana ___ ___ duermo hasta las diez.",
              "respuestas": [["casi"], ["siempre"]],
              "banco": ["casi", "nunca", "siempre", "a veces", "normalmente"],
              "mal": ["«Bijna» is <b>casi</b>.",
                      "«Bijna altijd» = casi <b>siempre</b>. Let op: <i>casi nunca</i> "
                      "betekent net het omgekeerde."]},
    "opciones": [
      ("Los fines de semana casi siempre duermo hasta las diez.", True, None),
      ("Los fines de semana casi nunca duermo hasta las diez.", False,
       "Dat is het omgekeerde: <i>casi nunca</i> = bijna nooit."),
    ],
    "acepta": [r"(siempre|normalmente|a\s+veces|casi\s+nunca|nunca|casi\s+siempre)",
               r"duermo|me\s+levanto"],
    "pista": "Kies een frequentiewoord: siempre · normalmente · a veces · "
             "casi nunca · nunca.",
    "modelo": "Los fines de semana casi siempre duermo hasta las diez."},

   {"di": "Yo igual. Entonces, ¿mañana a las cuatro y media en la plaza?",
    "nl": "Ik ook. Dus morgen om half vijf op het plein?",
    "meta": "Bevestig de afspraak.",
    "hueco": {"marco": "___, ___ vemos mañana.",
              "respuestas": [["vale", "sí"], ["nos"]],
              "banco": ["vale", "no", "nos", "me", "te"],
              "mal": ["Afspraken bevestig je met <b>vale</b> of <b>de acuerdo</b>.",
                      "«Tot ziens» is <b>nos vemos</b> — wij zien elkáár."]},
    "opciones": [
      ("Vale, nos vemos mañana.", True, None),
      ("Vale, me veo mañana.", False,
       "<b>Nos vemos</b> — jullie zien elkáár, niet jij jezelf."),
    ],
    "acepta": [r"(vale|de\s+acuerdo|perfecto|s[ií])", r"nos\s+vemos|hasta\s+ma[ñn]ana"],
    "pista": "«Vale» + «nos vemos mañana» of «hasta mañana».",
    "modelo": "Vale, nos vemos mañana."},
  ],
  "final": "¡Genial! Hasta mañana entonces. ¡Que descanses!",
  "final_nl": "Top! Tot morgen dan. Slaap lekker!",
 },

 # ── U4 · Me gusta · València ──────────────────────────────────────────────
 4: {
  "titulo": "El plan del finde",
  "lugar": "València · en la playa de la Malvarrosa",
  "tu": "Tú",
  "otro": "Diego",
  "otro_avatar": "🎧",
  "mision": "Maak samen een plan voor het weekend: zeg wat je graag doet, wat "
            "je níet leuk vindt, en stel iets voor.",
  "mision_es": "Habla de tus gustos y propón un plan para el finde.",
  "pasos": [
   {"di": "¿Qué te gusta hacer en tu tiempo libre?",
    "nl": "Wat doe je graag in je vrije tijd?",
    "meta": "Zeg wat je graag doet. Let goed op de vorm van «gustar».",
    "hueco": {"marco": "___ ___ escuchar música y nadar.",
              "respuestas": [["me"], ["gusta"]],
              "banco": ["me", "yo", "gusta", "gustan", "gusto"],
              "mal": ["Het is omgekeerd in het Spaans: <b>me</b> gusta, «het bevalt mij».",
                      "Na <i>me</i> staat een werkwoord in de infinitief → enkelvoud: "
                      "<b>gusta</b>."]},
    "opciones": [
      ("Me gusta escuchar música y nadar.", True, None),
      ("Yo gusto escuchar música y nadar.", False,
       "«Ik vind leuk» is <b>me gusta</b>, nooit «yo gusto»."),
      ("Me gustan escuchar música y nadar.", False,
       "Bij een werkwoord blijft het <b>me gusta</b>, in het enkelvoud."),
    ],
    "acepta": [r"me\s+(gusta|encanta)\s+\w+"],
    "pista": "«Me gusta + werkwoord» of «me encanta + werkwoord».",
    "modelo": "Me gusta escuchar música y nadar."},

   {"di": "¡A mí también! ¿Y los deportes? ¿Te gusta el fútbol?",
    "nl": "Ik ook! En sport? Vind je voetbal leuk?",
    "meta": "Zeg dat je het niet leuk vindt, maar noem iets wat je wél leuk vindt.",
    "hueco": {"marco": "No mucho, ___ me ___ los videojuegos.",
              "respuestas": [["pero"], ["gustan"]],
              "banco": ["pero", "y", "gusta", "gustan", "encanta"],
              "mal": ["Twee dingen die tegen elkaar in gaan verbind je met <b>pero</b>.",
                      "<i>Los videojuegos</i> is meervoud → <b>me gustan</b>, met -n."]},
    "opciones": [
      ("No mucho, pero me gustan los videojuegos.", True, None),
      ("No mucho, pero me gusta los videojuegos.", False,
       "Meervoud: <b>me gustan</b> los videojuegos."),
      ("No mucho, pero yo gusto los videojuegos.", False,
       "Nooit «yo gusto». Bij meervoud: <b>me gustan</b>."),
    ],
    "acepta": [r"me\s+gustan\s+l[oa]s", r"prefiero\s+\w+", r"me\s+encantan?\s+"],
    "pista": "Meer dan één ding → <b>me gustan</b>. Of gebruik «prefiero…».",
    "modelo": "No mucho, pero me gustan los videojuegos."},

   {"di": "Oye, ¿y qué tal si vamos al cine el sábado?",
    "nl": "Zeg, wat als we zaterdag naar de film gaan?",
    "meta": "Ga akkoord en stel een uur voor.",
    "hueco": {"marco": "¡___! ¿___ qué hora quedamos?",
              "respuestas": [["vale", "genial"], ["a"]],
              "banco": ["vale", "no", "a", "en", "de"],
              "mal": ["Instemmen doe je met <b>vale</b>, <b>genial</b> of <b>de acuerdo</b>.",
                      "«Hoe laat» is <b>¿a qué hora?</b>"]},
    "opciones": [
      ("¡Vale! ¿A qué hora quedamos?", True, None),
      ("¡Vale! ¿En qué hora quedamos?", False,
       "Het is <b>¿a qué hora?</b> — met <i>a</i>."),
    ],
    "acepta": [r"(vale|genial|guay|de\s+acuerdo|perfecto)", r"a\s+qu[eé]\s+hora"],
    "pista": "Zeg «Vale» en vraag dan «¿A qué hora…?».",
    "modelo": "¡Vale! ¿A qué hora quedamos?"},

   {"di": "¿A las siete? Después podemos tomar una horchata.",
    "nl": "Om zeven uur? Daarna kunnen we een horchata drinken.",
    "meta": "Zeg dat je die avond niet kan en geef de reden.",
    "hueco": {"marco": "No ___ a las siete ___ tengo que estudiar.",
              "respuestas": [["puedo"], ["porque"]],
              "banco": ["puedo", "puedes", "porque", "por qué", "luego"],
              "mal": ["Bij <i>yo</i>: <b>puedo</b> (o → ue).",
                      "«Want» én «omdat» zijn allebei <b>porque</b>, aan elkaar en zonder accent."]},
    "opciones": [
      ("No puedo a las siete porque tengo que estudiar.", True, None),
      ("No puedo a las siete por qué tengo que estudiar.", False,
       "<b>Porque</b> aan elkaar en zonder accent — dat is het antwoord. "
       "<i>Por qué</i> met accent is de vráág."),
      ("No puedo a las siete, luego tengo que estudiar.", False,
       "«Want» is <b>porque</b>. <i>Luego</i> betekent «later»."),
    ],
    "acepta": [r"no\s+puedo", r"porque\s+\w+"],
    "pista": "«No puedo … porque …» — let op het aan elkaar geschreven <i>porque</i>.",
    "modelo": "No puedo a las siete porque tengo que estudiar."},

   {"di": "Vale, ¿y a las nueve entonces?",
    "nl": "Oké, en om negen uur dan?",
    "meta": "Stem in en zeg dat je er zin in hebt.",
    "hueco": {"marco": "¡___! Me ___ el plan.",
              "respuestas": [["perfecto", "genial", "vale"], ["encanta", "gusta"]],
              "banco": ["perfecto", "aburrido", "encanta", "encantan", "odio"],
              "mal": ["Iets positiefs: perfecto · genial · vale.",
                      "<i>El plan</i> is enkelvoud → <b>me encanta</b> (of <i>me gusta</i>)."]},
    "opciones": [
      ("¡Perfecto! Me encanta el plan.", True, None),
      ("¡Perfecto! Me encantan el plan.", False,
       "<i>El plan</i> is enkelvoud: <b>me encanta</b>, zonder -n."),
    ],
    "acepta": [r"(perfecto|genial|guay|vale)", r"me\s+(encanta|gusta)"],
    "pista": "«¡Perfecto!» + «me encanta el plan».",
    "modelo": "¡Perfecto! Me encanta el plan."},
  ],
  "final": "¡Genial! Nos vemos el sábado a las nueve. ¡Hasta luego!",
  "final_nl": "Top! Tot zaterdag om negen uur. Tot dan!",
 },

 5: {
  "titulo": "En el restaurante",
  "lugar": "Ciudad de México · un restaurante en la Roma",
  "tu": "Tú, de klant",
  "otro": "El mesero",
  "otro_avatar": "🧑‍🍳",
  "mision": "Bestel een volledige maaltijd: een tafel, iets te drinken, een "
            "eerste gerecht, een hoofdgerecht en een nagerecht. Vraag daarna "
            "de rekening.",
  "mision_es": "Pide una comida completa y, al final, la cuenta.",
  "pasos": [
   {"di": "¡Buenas tardes! Bienvenido. ¿Mesa para cuántas personas?",
    "nl": "Goedemiddag! Welkom. Een tafel voor hoeveel personen?",
    "meta": "Vraag een tafel voor twee.",
    "hueco": {"marco": "___ mesa ___ dos, por favor.",
              "respuestas": [["una"], ["para"]],
              "banco": ["un", "una", "para", "por", "de"],
              "mal": ["<b>Mesa</b> is vrouwelijk — het lidwoord moet meeveranderen.",
                      "«Voor twee personen» is <b>para</b> dos. <i>Por</i> betekent iets anders."]},
    "opciones": [
      ("Una mesa para dos, por favor.", True, None),
      ("Un mesa para dos, por favor.", False,
       "<b>Mesa</b> is vrouwelijk: <i>una</i> mesa."),
    ],
    "acepta": [r"(una\s+)?mesa\s+para\s+(dos|2)", r"para\s+(dos|2)\s+personas",
               r"somos\s+(dos|2)"],
    "pista": "Begin met «Una mesa para…» en zeg hoeveel personen.",
    "modelo": "Una mesa para dos, por favor."},

   {"di": "Perfecto, por aquí. Aquí tienen la carta. ¿Qué van a tomar?",
    "nl": "Prima, deze kant op. Hier is de kaart. Wat wilt u drinken?",
    "meta": "Bestel iets te drinken. Beleefd graag.",
    "hueco": {"marco": "¿___ ___ un agua, por favor?",
              "respuestas": [["me"], ["pone", "trae"]],
              "banco": ["me", "yo", "pone", "trae", "gusta"],
              "mal": ["Het is <b>me</b> pone — «zet u míj». «Yo pone» bestaat niet.",
                      "Gebruik <b>pone</b> (zet u me) of <b>trae</b> (brengt u me)."]},
    "opciones": [
      ("¿Me pone un agua, por favor?", True, None),
      ("Quiero un agua.", False,
       "Inhoudelijk juist, maar het klinkt kortaf. Zet er <b>por favor</b> bij, "
       "of gebruik <b>¿me pone…?</b>"),
      ("Yo gusto un refresco.", False,
       "«Ik wil» is niet «yo gusto». Gebruik <b>quiero</b>, <b>para mí</b> of "
       "<b>¿me pone…?</b> — en <i>me gusta</i> betekent «ik vind lekker»."),
    ],
    "acepta": [r"(me\s+pone|me\s+trae|quiero|para\s+m[ií]|voy\s+a\s+tomar)",
               r"(un|una|el|la)\s+(agua|refresco|zumo|caf[eé]|t[eé]|leche)"],
    "pista": "Kies uit: el agua · el refresco · el zumo · el café · el té. "
             "Zeg het met «¿Me pone…?» of «Para mí…».",
    "modelo": "¿Me pone un agua, por favor?"},

   {"di": "Muy bien. De primer plato tenemos sopa, ensalada y guacamole con totopos.",
    "nl": "Heel goed. Als voorgerecht hebben we soep, salade en guacamole met chips.",
    "meta": "Kies een voorgerecht.",
    "hueco": {"marco": "Para ___, ___ sopa.",
              "respuestas": [["mí", "mi"], ["la"]],
              "banco": ["mí", "yo", "la", "el", "una"],
              "mal": ["Na een voorzetsel wordt <i>yo</i> → <b>mí</b>: «para mí».",
                      "<b>La sopa</b> — dit woord is vrouwelijk."]},
    "opciones": [
      ("Para mí, la sopa.", True, None),
      ("Para mí, el sopa.", False,
       "<b>La sopa</b> — dit woord is vrouwelijk."),
      ("Yo quiero la sopa porque tengo hambre y la sopa está muy rico.",
       False,
       "Bijna! Maar <b>la sopa</b> is vrouwelijk, dus: «está muy <i>rica</i>»."),
    ],
    "acepta": [r"(para\s+m[ií]|quiero|me\s+pone|voy\s+a\s+tomar)",
               r"(la\s+)?(sopa|ensalada|guacamole)"],
    "pista": "Zeg «Para mí, …» en kies: la sopa · la ensalada · el guacamole.",
    "modelo": "Para mí, la sopa."},

   {"di": "¿Y de plato fuerte? Hay tacos de pollo, pescado a la plancha y arroz con verduras.",
    "nl": "En als hoofdgerecht? Er zijn kiptaco's, gegrilde vis en rijst met groenten.",
    "meta": "Kies een hoofdgerecht. Zeg er iets bij: waarom, of hoe je het wil.",
    "hueco": {"marco": "Quiero los tacos de pollo, por favor. Me ___ mucho ___ son ricos.",
              "respuestas": [["gustan"], ["porque"]],
              "banco": ["gusta", "gustan", "porque", "por qué", "luego"],
              "mal": ["Meer dan één ding → <b>me gustan</b>, met -n.",
                      "«Want» én «omdat» zijn allebei <b>porque</b>, aan elkaar en zonder accent."]},
    "opciones": [
      ("Quiero los tacos de pollo, por favor. Me gustan mucho.", True, None),
      ("Quiero los tacos de pollo. Yo gusto mucho.", False,
       "Bijna. «Ik vind ze lekker» is <b>me gustan</b> — bij meerdere dingen "
       "wordt het <i>gustan</i>."),
      ("Quiero el pescado, luego no como carne.", False,
       "«Dus» is niet <i>luego</i> (= later). Hier past <b>porque</b>: "
       "«…porque no como carne»."),
    ],
    "acepta": [r"(quiero|para\s+m[ií]|me\s+pone|voy\s+a\s+tomar)",
               r"(tacos|pescado|arroz|pollo)"],
    "pista": "Kies: los tacos de pollo · el pescado · el arroz. Voeg er iets "
             "aan toe met «me gusta(n)» of «porque…».",
    "modelo": "Quiero los tacos de pollo, por favor. Me gustan mucho porque son ricos."},

   {"di": "¡Que aproveche!  …  ¿Todo bien? ¿Van a tomar postre? Hay churros y fruta.",
    "nl": "Eet smakelijk!  …  Alles goed? Neemt u een nagerecht? Er zijn churros en fruit.",
    "meta": "Zeg dat het lekker was en kies een nagerecht — of sla het beleefd af.",
    "hueco": {"marco": "___ muy rico, gracias. De postre, ___ churros.",
              "respuestas": [["está", "esta"], ["los"]],
              "banco": ["está", "es", "los", "el", "las"],
              "mal": ["Hoe iets nú smaakt is <b>está</b>, niet <i>es</i>.",
                      "<b>Los churros</b> — meervoud."]},
    "opciones": [
      ("Está muy rico, gracias. De postre, los churros.", True, None),
      ("Está muy rico, gracias. De postre, el churros.", False,
       "<b>Los churros</b> — het is meervoud."),
      ("No, gracias. Estoy lleno.", True, None),
    ],
    "acepta": [r"(churros|fruta|manzana|pl[aá]tano|fresa|uvas|pi[ñn]a)",
               r"no,?\s*gracias"],
    "pista": "Zeg eerst dat het lekker is («está muy rico») en kies dan: "
             "los churros · la fruta. Of sla af met «No, gracias».",
    "modelo": "Está muy rico, gracias. De postre, los churros."},

   {"di": "Claro que sí. ¿Algo más?",
    "nl": "Natuurlijk. Nog iets anders?",
    "meta": "Vraag de rekening.",
    "hueco": {"marco": "¿Me ___ ___ cuenta, por favor?",
              "respuestas": [["trae", "pone"], ["la"]],
              "banco": ["trae", "pone", "la", "el", "una"],
              "mal": ["<b>Trae</b> = brengt u me. Dat is wat je hier vraagt.",
                      "<b>La cuenta</b> — vrouwelijk."]},
    "opciones": [
      ("¿Me trae la cuenta, por favor?", True, None),
      ("¿Me trae el cuenta, por favor?", False,
       "<b>La cuenta</b> — vrouwelijk."),
    ],
    "acepta": [r"(la\s+)?cuenta"],
    "pista": "Het woord dat je zoekt staat bij «restaurante» in je woordenlijst: "
             "la c___.",
    "modelo": "¿Me trae la cuenta, por favor?"},
  ],
  "final": "Son doscientos ochenta pesos. ¡Muchas gracias y hasta pronto!",
  "final_nl": "Dat is tweehonderdtachtig peso. Hartelijk dank en tot ziens!",
 },

 # ── U6 · De tiendas · México (mercados) ───────────────────────────────────
 6: {
  "titulo": "En la tienda de ropa",
  "lugar": "Ciudad de México · una tienda en la Condesa",
  "tu": "Tú, de klant",
  "otro": "La dependienta",
  "otro_avatar": "\U0001F455",
  "mision": "Koop een kledingstuk: zeg wat je zoekt en in welke kleur, vraag "
            "je maat, pas het, vraag de prijs en beslis.",
  "mision_es": "Compra una prenda: color, talla, probador y precio.",
  "pasos": [
   {"di": "\u00a1Buenas! \u00bfQu\u00e9 desea?",
    "nl": "Goeiedag! Waarmee kan ik u helpen?",
    "meta": "Zeg wat je zoekt en in welke kleur.",
    "hueco": {"marco": "Busco ___ camiseta ___.",
              "respuestas": [["una"], ["negra"]],
              "banco": ["un", "una", "negro", "negra", "azul"],
              "mal": ["<b>Camiseta</b> is vrouwelijk: <i>una</i> camiseta.",
                      "De kleur past zich aan: bij <i>camiseta</i> hoort <b>negra</b>."]},
    "opciones": [
      ("Busco una camiseta negra.", True, None),
      ("Busco un camiseta negro.", False,
       "Twee keer mis: <b>una</b> camiseta (vrouwelijk) en dus ook <b>negra</b>."),
    ],
    "acepta": [r"busco\s+(un|una)\s+\w+", r"quiero\s+(un|una)\s+\w+",
               r"(camiseta|camisa|jersey|sudadera|chaqueta|pantalones|falda|vestido)"],
    "pista": "«Busco una …» + kledingstuk + kleur. Let op: de kleur volgt het woord.",
    "modelo": "Busco una camiseta negra."},

   {"di": "Tenemos varias. \u00bfQu\u00e9 talla usa?",
    "nl": "We hebben er verschillende. Welke maat hebt u?",
    "meta": "Zeg je maat.",
    "hueco": {"marco": "___ la ___ eme.",
              "respuestas": [["uso", "llevo"], ["talla"]],
              "banco": ["uso", "soy", "talla", "n\u00famero", "medida"],
              "mal": ["Voor kleding zeg je <b>uso</b> of <b>llevo</b> la talla\u2026",
                      "Bij kleding is het <b>la talla</b>; <i>el n\u00famero</i> is voor schoenen."]},
    "opciones": [
      ("Uso la talla eme.", True, None),
      ("Soy la talla eme.", False,
       "Met <i>ser</i> zeg je wie je b\u00e9nt. Voor een maat: <b>uso</b> of <b>llevo</b>."),
      ("Uso el n\u00famero eme.", False,
       "<b>La talla</b> is voor kleren; <i>el n\u00famero</i> gebruik je voor schoenen."),
    ],
    "acepta": [r"(uso|llevo)\s+la\s+talla", r"\btalla\b", r"\b(eme|ese|ele|\d+)\b"],
    "pista": "«Uso la talla …» \u2014 eme, ese of ele.",
    "modelo": "Uso la talla eme."},

   {"di": "Aqu\u00ed tiene. El probador est\u00e1 al fondo, a la derecha.",
    "nl": "Alstublieft. De paskamer is achteraan, rechts.",
    "meta": "Vraag of je het mag passen.",
    "hueco": {"marco": "\u00bf___ ___?",
              "respuestas": [["puedo"], ["prob\u00e1rmela", "probarmela", "prob\u00e1rmelo"]],
              "banco": ["puedo", "puedes", "prob\u00e1rmela", "probar", "llevar"],
              "mal": ["Bij <i>yo</i>: <b>puedo</b> (o \u2192 ue).",
                      "Het is <b>prob\u00e1rmela</b>: passen + mij + haar (de camiseta)."]},
    "opciones": [
      ("\u00bfPuedo prob\u00e1rmela?", True, None),
      ("\u00bfPuedo prob\u00e1rmelo?", False,
       "Het gaat over <i>la camiseta</i>, vrouwelijk: <b>prob\u00e1rmela</b>."),
    ],
    "acepta": [r"puedo\s+prob", r"\bprob[a\u00e1]r"],
    "pista": "«\u00bfPuedo prob\u00e1rme\u2026?» \u2014 en dan -la voor <i>la camiseta</i>.",
    "modelo": "\u00bfPuedo prob\u00e1rmela?"},

   {"di": "\u00a1Claro! \u2026 \u00bfQu\u00e9 tal le queda?",
    "nl": "Natuurlijk! \u2026 Hoe zit hij?",
    "meta": "Zeg dat hij goed zit, en vraag de prijs.",
    "hueco": {"marco": "Me ___ bien. \u00bf___ cuesta?",
              "respuestas": [["queda"], ["cu\u00e1nto", "cuanto"]],
              "banco": ["queda", "quedan", "cu\u00e1nto", "c\u00f3mo", "qu\u00e9"],
              "mal": ["\u00c9\u00e9n kledingstuk \u2192 <b>me queda</b>, zonder -n.",
                      "Naar een prijs vraag je met <b>\u00bfcu\u00e1nto cuesta?</b>"]},
    "opciones": [
      ("Me queda bien. \u00bfCu\u00e1nto cuesta?", True, None),
      ("Me quedan bien. \u00bfCu\u00e1nto cuesta?", False,
       "\u00c9\u00e9n camiseta \u2192 <b>me queda</b>. Met <i>quedan</i> praat je over meerdere stuks."),
      ("Me queda bien. \u00bfC\u00f3mo cuesta?", False,
       "Naar een prijs vraag je met <b>cu\u00e1nto</b>, niet <i>c\u00f3mo</i>."),
    ],
    "acepta": [r"me\s+queda", r"cu[a\u00e1]nto\s+cuesta"],
    "pista": "Twee stukken: «Me queda bien» en «\u00bfCu\u00e1nto cuesta?».",
    "modelo": "Me queda bien. \u00bfCu\u00e1nto cuesta?"},

   {"di": "Doscientos cincuenta pesos. Est\u00e1 de rebajas.",
    "nl": "Tweehonderdvijftig peso. Hij is afgeprijsd.",
    "meta": "Beslis: je neemt hem.",
    "hueco": {"marco": "Vale, ___ ___ llevo.",
              "respuestas": [["me"], ["la"]],
              "banco": ["me", "te", "la", "lo", "los"],
              "mal": ["De vaste uitdrukking is <b>me lo/la llevo</b> \u2014 «ik neem hem mee».",
                      "Het gaat over <i>la camiseta</i>: <b>la</b>."]},
    "opciones": [
      ("Vale, me la llevo.", True, None),
      ("Vale, me lo llevo.", False,
       "Het gaat over <i>la camiseta</i>, vrouwelijk: <b>me la llevo</b>."),
    ],
    "acepta": [r"me\s+l[oa]\s+llevo", r"\bllevo\b"],
    "pista": "De vaste uitdrukking: «me la llevo».",
    "modelo": "Vale, me la llevo."},
  ],
  "final": "\u00a1Perfecto! Pase por la caja, por favor. \u00a1Que la disfrute!",
  "final_nl": "Perfect! Gaat u naar de kassa, alstublieft. Veel plezier ermee!",
 },

 # ── U7 · Mi casa y mi barrio · Colombia (Cartagena) ───────────────────────
 7: {
  "titulo": "\u00bfPor d\u00f3nde se va?",
  "lugar": "Cartagena \u00b7 en la calle, cerca de la plaza",
  "tu": "T\u00fa, die de weg zoekt",
  "otro": "Valen",
  "otro_avatar": "\U0001F5FA\uFE0F",
  "mision": "Vraag de weg naar de bakker, begrijp de uitleg, en vertel daarna "
            "waar jij woont en hoe je huis eruitziet.",
  "mision_es": "Pregunta el camino y describe d\u00f3nde vives.",
  "pasos": [
   {"di": "\u00a1Hola! Te veo perdido. \u00bfBuscas algo?",
    "nl": "Hallo! Je lijkt verdwaald. Zoek je iets?",
    "meta": "Vraag waar de bakkerij is.",
    "hueco": {"marco": "S\u00ed, \u00bf___ ___ la panader\u00eda?",
              "respuestas": [["d\u00f3nde", "donde"], ["est\u00e1", "esta"]],
              "banco": ["d\u00f3nde", "c\u00f3mo", "est\u00e1", "es", "hay"],
              "mal": ["«Waar» is <b>d\u00f3nde</b>, met accent in een vraag.",
                      "De plaats van iets vraag je met <b>est\u00e1</b>, niet met <i>es</i>."]},
    "opciones": [
      ("S\u00ed, \u00bfd\u00f3nde est\u00e1 la panader\u00eda?", True, None),
      ("S\u00ed, \u00bfd\u00f3nde es la panader\u00eda?", False,
       "Waar iets is, gaat met <b>estar</b>: «\u00bfd\u00f3nde est\u00e1\u2026?»"),
    ],
    "acepta": [r"d[o\u00f3]nde\s+est[a\u00e1]", r"hay\s+una?\s+\w+"],
    "pista": "«\u00bfD\u00f3nde est\u00e1 \u2026?» of «\u00bfHay una panader\u00eda por aqu\u00ed?»",
    "modelo": "S\u00ed, \u00bfd\u00f3nde est\u00e1 la panader\u00eda?"},

   {"di": "Sigue todo recto y gira a la izquierda en el sem\u00e1foro. \u00bfEntiendes?",
    "nl": "Ga rechtdoor en sla links af bij het stoplicht. Begrijp je het?",
    "meta": "Herhaal het om zeker te zijn: rechtdoor en dan links.",
    "hueco": {"marco": "Entonces todo ___ y luego a la ___.",
              "respuestas": [["recto"], ["izquierda"]],
              "banco": ["recto", "derecha", "izquierda", "esquina", "cerca"],
              "mal": ["«Rechtdoor» is <b>todo recto</b>.",
                      "Zij zei <b>izquierda</b> (links). <i>Derecha</i> is rechts."]},
    "opciones": [
      ("Entonces todo recto y luego a la izquierda.", True, None),
      ("Entonces todo recto y luego a la derecha.", False,
       "Ze zei <b>a la izquierda</b> \u2014 links, niet rechts."),
    ],
    "acepta": [r"todo\s+recto", r"a\s+la\s+izquierda"],
    "pista": "De twee stukken uit haar uitleg: «todo recto» en «a la izquierda».",
    "modelo": "Entonces todo recto y luego a la izquierda."},

   {"di": "\u00a1Exacto! Est\u00e1 al lado del banco. \u00bfT\u00fa vives por aqu\u00ed?",
    "nl": "Precies! Ze ligt naast de bank. Woon jij hier in de buurt?",
    "meta": "Zeg waar je woont en op welke verdieping.",
    "hueco": {"marco": "Vivo ___ un piso, ___ el tercer piso.",
              "respuestas": [["en"], ["en"]],
              "banco": ["en", "a", "de", "sobre", "con"],
              "mal": ["Wonen \u00ednergens: <b>vivo en</b>.",
                      "Ook een verdieping krijgt <b>en</b>: «en el tercer piso»."]},
    "opciones": [
      ("Vivo en un piso, en el tercer piso.", True, None),
      ("Vivo a un piso, en el tercer piso.", False,
       "Wonen gaat met <b>en</b>, niet met <i>a</i>."),
    ],
    "acepta": [r"vivo\s+en\s+\w+", r"(piso|casa|apartamento)"],
    "pista": "«Vivo en \u2026» \u2014 una casa, un piso of un apartamento.",
    "modelo": "Vivo en un piso, en el tercer piso."},

   {"di": "\u00bfY c\u00f3mo es tu casa? \u00bfEs grande?",
    "nl": "En hoe is je huis? Is het groot?",
    "meta": "Beschrijf je huis: zeg hoeveel kamers er zijn.",
    "hueco": {"marco": "No es muy grande. ___ tres ___ y una cocina.",
              "respuestas": [["hay"], ["habitaciones"]],
              "banco": ["hay", "son", "est\u00e1n", "habitaciones", "muebles"],
              "mal": ["«Er is / er zijn» is <b>hay</b> \u2014 altijd dezelfde vorm.",
                      "Kamers zijn <b>habitaciones</b> (of <i>dormitorios</i> voor slaapkamers)."]},
    "opciones": [
      ("No es muy grande. Hay tres habitaciones y una cocina.", True, None),
      ("No es muy grande. Son tres habitaciones y una cocina.", False,
       "Om te zeggen d\u00e1t iets er is, gebruik je <b>hay</b>."),
      ("No es muy grande. Est\u00e1n tres habitaciones y una cocina.", False,
       "<b>Hay</b> zegt d\u00e1t iets bestaat; <i>est\u00e1</i> zegt w\u00e1\u00e1r iets is."),
    ],
    "acepta": [r"\bhay\s+\w+", r"(habitacion|dormitorio|cocina|sal[o\u00f3]n|ba[n\u00f1]o)"],
    "pista": "«Hay + aantal + kamers». Denk aan het verschil tussen <i>hay</i> en <i>est\u00e1</i>.",
    "modelo": "No es muy grande. Hay tres habitaciones y una cocina."},

   {"di": "\u00a1Qu\u00e9 bien! \u00bfY tienes tienda cerca?",
    "nl": "Wat fijn! En heb je een winkel in de buurt?",
    "meta": "Zeg wat er naast of dichtbij je huis ligt.",
    "hueco": {"marco": "S\u00ed, hay un supermercado ___ ___ de mi casa.",
              "respuestas": [["al"], ["lado"]],
              "banco": ["al", "el", "lado", "cerca", "delante"],
              "mal": ["De uitdrukking is <b>al lado de</b> \u2014 a + el wordt <i>al</i>.",
                      "Het woord dat je zoekt is <b>lado</b>: al <i>lado</i> de."]},
    "opciones": [
      ("S\u00ed, hay un supermercado al lado de mi casa.", True, None),
      ("S\u00ed, hay un supermercado a el lado de mi casa.", False,
       "<i>A + el</i> wordt altijd <b>al</b>: «al lado de»."),
    ],
    "acepta": [r"(al\s+lado|cerca|enfrente|detr[a\u00e1]s|delante)\s*(de)?",
               r"hay\s+un"],
    "pista": "Kies een plaatsbepaling: al lado de \u00b7 cerca de \u00b7 enfrente de.",
    "modelo": "S\u00ed, hay un supermercado al lado de mi casa."},
  ],
  "final": "\u00a1Qu\u00e9 pr\u00e1ctico! Bueno, la panader\u00eda cierra a las dos. \u00a1Corre!",
  "final_nl": "Wat handig! Goed, de bakker sluit om twee uur. Loop maar snel!",
 },

 # ── U8 · \u00bfQu\u00e9 has hecho? \u00b7 Per\u00fa (Cusco) ──────────────────────────────
 8: {
  "titulo": "El diario de viaje",
  "lugar": "Cusco \u00b7 en el hostal, por la noche",
  "tu": "T\u00fa, terug van een dagtocht",
  "otro": "Nina",
  "otro_avatar": "\U0001F3D4\uFE0F",
  "mision": "Vertel wat je vandaag gedaan hebt. Gebruik de voltooide tijd "
            "(he visitado, he comido\u2026) en zeg ook wat je n\u00f3g niet gedaan hebt.",
  "mision_es": "Cuenta qu\u00e9 has hecho hoy y qu\u00e9 no has hecho todav\u00eda.",
  "pasos": [
   {"di": "\u00a1Hola! \u00bfQu\u00e9 tal el d\u00eda? \u00bfQu\u00e9 has hecho?",
    "nl": "Hallo! Hoe was je dag? Wat heb je gedaan?",
    "meta": "Zeg wat je bezocht hebt. Gebruik de voltooide tijd.",
    "hueco": {"marco": "___ ___ las ruinas.",
              "respuestas": [["he"], ["visitado"]],
              "banco": ["he", "has", "visitado", "visito", "visitar"],
              "mal": ["Bij <i>yo</i> is het hulpwerkwoord <b>he</b>. <i>Has</i> is de jij-vorm.",
                      "Het voltooid deelwoord van <i>visitar</i> is <b>visitado</b>."]},
    "opciones": [
      ("He visitado las ruinas.", True, None),
      ("Has visitado las ruinas.", False,
       "<b>He</b> visitado \u2014 <i>has</i> zou over j\u00f3u gaan, niet over mij."),
      ("He visitar las ruinas.", False,
       "Na <i>he</i> komt het voltooid deelwoord: <b>visitado</b>."),
    ],
    "acepta": [r"he\s+\w+[ai]do", r"he\s+(hecho|visto|dicho|escrito|vuelto|puesto|roto|abierto)"],
    "pista": "«He + voltooid deelwoord»: visitado \u00b7 comido \u00b7 subido.",
    "modelo": "He visitado las ruinas."},

   {"di": "\u00a1Qu\u00e9 envidia! \u00bfY has visto llamas?",
    "nl": "Wat jaloers! En heb je lama's gezien?",
    "meta": "Zeg ja \u2014 en let op: <i>ver</i> heeft een onregelmatig deelwoord.",
    "hueco": {"marco": "S\u00ed, ___ ___ muchas llamas.",
              "respuestas": [["he"], ["visto"]],
              "banco": ["he", "has", "visto", "vido", "veido"],
              "mal": ["Bij <i>yo</i>: <b>he</b>.",
                      "<i>Ver</i> is onregelmatig: het deelwoord is <b>visto</b>, niet «veido»."]},
    "opciones": [
      ("S\u00ed, he visto muchas llamas.", True, None),
      ("S\u00ed, he veido muchas llamas.", False,
       "<i>Ver</i> is onregelmatig: <b>visto</b>."),
    ],
    "acepta": [r"he\s+visto"],
    "pista": "Acht onregelmatige: hecho \u00b7 <b>visto</b> \u00b7 dicho \u00b7 escrito \u00b7 vuelto \u00b7 "
             "puesto \u00b7 abierto \u00b7 roto.",
    "modelo": "S\u00ed, he visto muchas llamas."},

   {"di": "\u00bfY has probado el ceviche? Es t\u00edpico de aqu\u00ed.",
    "nl": "En heb je ceviche geproefd? Dat is hier typisch.",
    "meta": "Zeg dat je dat n\u00f3g niet gedaan hebt.",
    "hueco": {"marco": "No, ___ ___ lo he probado.",
              "respuestas": [["todav\u00eda", "todavia"], ["no"]],
              "banco": ["todav\u00eda", "ya", "no", "nunca", "siempre"],
              "mal": ["«Nog niet» begint met <b>todav\u00eda</b>.",
                      "De vaste combinatie is <b>todav\u00eda no</b>."]},
    "opciones": [
      ("No, todav\u00eda no lo he probado.", True, None),
      ("No, ya no lo he probado.", False,
       "<i>Ya</i> betekent «al». «Nog niet» is <b>todav\u00eda no</b>."),
    ],
    "acepta": [r"todav[i\u00ed]a\s+no", r"nunca\s+(lo\s+)?he", r"no\s+lo\s+he"],
    "pista": "«Todav\u00eda no \u2026» of «Nunca he \u2026».",
    "modelo": "No, todav\u00eda no lo he probado."},

   {"di": "\u00a1Pues tienes que probarlo! \u00bfHas estado alguna vez en la selva?",
    "nl": "Dan moet je het proberen! Ben je ooit in het regenwoud geweest?",
    "meta": "Zeg dat je daar nog nooit geweest bent.",
    "hueco": {"marco": "No, ___ ___ estado en la selva.",
              "respuestas": [["nunca"], ["he"]],
              "banco": ["nunca", "siempre", "he", "has", "estoy"],
              "mal": ["«Nooit» is <b>nunca</b>.",
                      "Bij <i>yo</i>: <b>he</b> estado."]},
    "opciones": [
      ("No, nunca he estado en la selva.", True, None),
      ("No, nunca estoy en la selva.", False,
       "Over je hele leven tot nu gebruik je de voltooide tijd: <b>nunca he estado</b>."),
    ],
    "acepta": [r"nunca\s+he", r"todav[i\u00ed]a\s+no"],
    "pista": "«Nunca he estado \u2026» \u2014 met <i>he</i> erbij.",
    "modelo": "No, nunca he estado en la selva."},

   {"di": "\u00bfY qu\u00e9 tiempo ha hecho hoy en la monta\u00f1a?",
    "nl": "En wat voor weer was het vandaag in de bergen?",
    "meta": "Zeg wat voor weer het was.",
    "hueco": {"marco": "Por la ma\u00f1ana ___ sol, pero luego ___ mucho fr\u00edo.",
              "respuestas": [["ha hecho", "hac\u00eda", "hacia", "hizo"], ["ha hecho", "hac\u00eda", "hacia", "hizo"]],
              "banco": ["hac\u00eda", "era", "estaba", "hizo", "ten\u00eda"],
              "mal": ["Het weer krijgt altijd <b>hacer</b>: «hac\u00eda sol».",
                      "Ook hier <b>hacer</b>: «hac\u00eda fr\u00edo». Nooit <i>era</i> of <i>estaba</i>."]},
    "opciones": [
      ("Por la ma\u00f1ana ha hecho sol, pero luego ha hecho mucho fr\u00edo.", True, None),
      ("Por la ma\u00f1ana ha sido sol, pero luego ha estado fr\u00edo.", False,
       "Het weer gaat met <b>hacer</b>: «ha hecho sol», «ha hecho fr\u00edo»."),
    ],
    "acepta": [r"(hac[i\u00ed]a|ha\s+hecho|hizo)\s+(sol|calor|fr[i\u00ed]o|viento)",
               r"(llov[i\u00ed]a|ha\s+llovido|nevaba)"],
    "pista": "Het weer krijgt <b>hacer</b>: hac\u00eda sol \u00b7 hac\u00eda fr\u00edo \u00b7 ha hecho viento.",
    "modelo": "Por la ma\u00f1ana ha hecho sol, pero luego ha hecho mucho fr\u00edo."},
  ],
  "final": "Suena a un d\u00eda perfecto. \u00a1Ma\u00f1ana el ceviche, entonces! Que descanses.",
  "final_nl": "Klinkt als een perfecte dag. Morgen dan de ceviche! Slaap lekker.",
 },
}
