#!/usr/bin/env python3
"""De rollenspellen van C4 «¡Bienvenidos al español!».

DRIE BEURTEN, NIET VIJF (auteur 2026-08-09)
C4 zit op pre-A1: veertien lesuren, geen vervoeging als systeem, alles op
chunks. Een scène van vijf beurten met invulgaten is daar te zwaar — de
leerling haakt af vóór hij iets gezegd heeft. Elke scène heeft hier dus **drie
beurten**, met kortere zinnen en één ding tegelijk in het gat.

DE CHUNK IS DE LEERSTOF
In C5 en C6+ oefent het gat een grammaticale keuze (un ↔ una, gusta ↔ gustan).
Hier oefent het meestal de chunk zélf: het stuk taal dat de leerling als geheel
moet onthouden, zoals het in de aflevering gezegd wordt. Daarom staan de
antwoorden bijna altijd letterlijk in de woordenschat van die unit.

De scène sluit aan bij de sitcom-aflevering van de unit, zodat de leerling
herkent wat hij gezien heeft.
"""

ROLES = {
 1: {
  "titulo": "¿Cómo te llamas?", "lugar": "La academia · el primer día",
  "tu": "Tú", "otro": "Julio", "otro_avatar": "👨‍🏫",
  "mision": "Stel jezelf voor aan de leerkracht en vraag zijn naam terug.",
  "mision_es": "Preséntate y pregunta cómo se llama él.",
  "pasos": [
   {"di": "¡Hola! ¿Cómo te llamas?", "nl": "Hallo! Hoe heet je?",
    "meta": "Zeg hoe je heet.",
    "hueco": {"marco": "___ ___ Lars.", "respuestas": [["me"], ["llamo"]],
              "banco": ["me", "te", "llamo", "llamas", "soy"],
              "mal": ["Het is <b>me</b> llamo.", "Bij <i>yo</i>: <b>llamo</b>."]},
    "opciones": [("Me llamo Lars.", True, None),
                 ("Te llamo Lars.", False, "<b>Me</b> llamo — <i>te</i> gaat over jou.")],
    "acepta": [r"me\s+llamo\s+\w+", r"soy\s+\w+"],
    "pista": "«Me llamo …» of «Soy …».", "modelo": "Me llamo Lars."},
   {"di": "Mucho gusto, Lars.", "nl": "Aangenaam, Lars.",
    "meta": "Vraag hoe hij heet.",
    "hueco": {"marco": "¿___ ___ llamas?", "respuestas": [["cómo", "como"], ["te"]],
              "banco": ["cómo", "qué", "te", "me", "se"],
              "mal": ["«Hoe» is <b>cómo</b>.", "Aan hém: <b>te</b> llamas."]},
    "opciones": [("¿Cómo te llamas?", True, None),
                 ("¿Cómo me llamo?", False, "Dan vraag je hoe jíj heet.")],
    "acepta": [r"c[oó]mo\s+te\s+llamas", r"y\s+t[uú]"],
    "pista": "De vraag uit de aflevering: ¿Cómo te …?", "modelo": "¿Cómo te llamas?"},
   {"di": "Me llamo Julio. ¡Bienvenido!", "nl": "Ik heet Julio. Welkom!",
    "meta": "Bedank hem.",
    "hueco": {"marco": "___ ___, Julio.", "respuestas": [["muchas"], ["gracias"]],
              "banco": ["muchas", "mucho", "gracias", "favor", "nada"],
              "mal": ["<b>Muchas</b> gracias — <i>gracias</i> is vrouwelijk meervoud.",
                      "Het woord is <b>gracias</b>."]},
    "opciones": [("Muchas gracias, Julio.", True, None),
                 ("Mucho gracias, Julio.", False, "Het is <b>muchas</b> gracias.")],
    "acepta": [r"gracias"],
    "pista": "«(Muchas) gracias».", "modelo": "Muchas gracias, Julio."}],
  "final": "De nada. ¡Hasta luego!", "final_nl": "Graag gedaan. Tot ziens!"},

 2: {
  "titulo": "¿Qué tal?", "lugar": "La academia · por la mañana",
  "tu": "Tú", "otro": "María", "otro_avatar": "☀️",
  "mision": "Groet, zeg hoe het gaat en neem afscheid.",
  "mision_es": "Saluda, di cómo estás y despídete.",
  "pasos": [
   {"di": "¡Buenos días! ¿Qué tal?", "nl": "Goedemorgen! Hoe gaat het?",
    "meta": "Groet terug en zeg dat het goed gaat.",
    "hueco": {"marco": "___ días. ___ bien, gracias.",
              "respuestas": [["buenos"], ["muy"]],
              "banco": ["buenos", "buenas", "muy", "mucho", "poco"],
              "mal": ["<i>Días</i> is mannelijk meervoud: <b>buenos</b> días.",
                      "«Heel goed» is <b>muy</b> bien."]},
    "opciones": [("Buenos días. Muy bien, gracias.", True, None),
                 ("Buenas días. Mucho bien, gracias.", False,
                  "Twee keer mis: <b>buenos</b> días en <b>muy</b> bien.")],
    "acepta": [r"buen[oa]s\s+d[ií]as", r"(muy\s+)?bien"],
    "pista": "«Buenos días» + «(Muy) bien, gracias».",
    "modelo": "Buenos días. Muy bien, gracias."},
   {"di": "Me alegro. Yo estoy un poco cansada.", "nl": "Fijn. Ik ben een beetje moe.",
    "meta": "Vraag haar hoe het gaat.",
    "hueco": {"marco": "¿___ ___?", "respuestas": [["cómo", "como"], ["estás", "estas"]],
              "banco": ["cómo", "qué", "estás", "estoy", "está"],
              "mal": ["«Hoe» is <b>cómo</b>.", "Aan haar: <b>estás</b>."]},
    "opciones": [("¿Cómo estás?", True, None),
                 ("¿Cómo estoy?", False, "Dan vraag je hoe het met jóú gaat.")],
    "acepta": [r"c[oó]mo\s+est[aá]s", r"qu[eé]\s+tal", r"y\s+t[uú]"],
    "pista": "«¿Cómo estás?» of «¿Qué tal?»", "modelo": "¿Cómo estás?"},
   {"di": "Bien, gracias. Bueno, me voy a clase.", "nl": "Goed, dank je. Ik ga naar de les.",
    "meta": "Neem afscheid.",
    "hueco": {"marco": "___ ___.", "respuestas": [["hasta"], ["luego"]],
              "banco": ["hasta", "adiós", "luego", "mañana", "gracias"],
              "mal": ["«Tot» is <b>hasta</b>.", "«Tot straks» is hasta <b>luego</b>."]},
    "opciones": [("Hasta luego.", True, None),
                 ("Hasta gracias.", False, "«Tot straks» is <b>hasta luego</b>.")],
    "acepta": [r"hasta\s+(luego|ma[ñn]ana)", r"adi[oó]s"],
    "pista": "Adiós · Hasta luego · Hasta mañana.", "modelo": "Hasta luego."}],
  "final": "¡Adiós, hasta mañana!", "final_nl": "Dag, tot morgen!"},

 3: {
  "titulo": "¿De dónde eres?", "lugar": "La academia · una clase nueva",
  "tu": "Tú", "otro": "La alumna", "otro_avatar": "🌍",
  "mision": "Zeg uit welk land je komt en vraag het terug.",
  "mision_es": "Di de dónde eres y pregúntalo tú también.",
  "pasos": [
   {"di": "¡Hola! ¿De dónde eres?", "nl": "Hallo! Waar kom je vandaan?",
    "meta": "Zeg uit welk land je komt.",
    "hueco": {"marco": "___ ___ Bélgica.", "respuestas": [["soy"], ["de"]],
              "banco": ["soy", "estoy", "de", "en", "a"],
              "mal": ["Herkomst gaat met <b>soy</b>.", "En met <b>de</b>: «soy de…»."]},
    "opciones": [("Soy de Bélgica.", True, None),
                 ("Soy en Bélgica.", False, "«Ik kom uit» is <b>soy de</b>.")],
    "acepta": [r"soy\s+de\s+\w+", r"soy\s+belga"],
    "pista": "«Soy de …» + je land.", "modelo": "Soy de Bélgica."},
   {"di": "¡Qué bien! Yo soy de Argelia.", "nl": "Wat leuk! Ik kom uit Algerije.",
    "meta": "Vraag welke talen zij spreekt.",
    "hueco": {"marco": "¿Qué ___ ___?", "respuestas": [["idiomas", "lenguas"], ["hablas"]],
              "banco": ["idiomas", "países", "hablas", "hablo", "habla"],
              "mal": ["Talen zijn <b>idiomas</b> (of <i>lenguas</i>).",
                      "Aan haar: <b>hablas</b>."]},
    "opciones": [("¿Qué idiomas hablas?", True, None),
                 ("¿Qué idiomas hablo?", False, "Dan vraag je wat jíj spreekt.")],
    "acepta": [r"qu[eé]\s+(idiomas|lenguas)\s+hablas", r"hablas\s+\w+"],
    "pista": "«¿Qué idiomas hablas?»", "modelo": "¿Qué idiomas hablas?"},
   {"di": "Hablo árabe, francés y un poco de español.", "nl": "Ik spreek Arabisch, Frans en een beetje Spaans.",
    "meta": "Zeg welke talen jij spreekt.",
    "hueco": {"marco": "Yo ___ neerlandés y ___ poco de español.",
              "respuestas": [["hablo"], ["un"]],
              "banco": ["hablo", "hablas", "un", "una", "mucho"],
              "mal": ["Bij <i>yo</i>: <b>hablo</b>.", "De uitdrukking is <b>un poco de</b>."]},
    "opciones": [("Yo hablo neerlandés y un poco de español.", True, None),
                 ("Yo hablas neerlandés y un poco de español.", False,
                  "Bij <i>yo</i> hoort <b>hablo</b>.")],
    "acepta": [r"hablo\s+\w+"],
    "pista": "«Hablo …» + de taal.", "modelo": "Yo hablo neerlandés y un poco de español."}],
  "final": "¡Muy bien! Poco a poco vas a hablar mucho español.",
  "final_nl": "Heel goed! Beetje bij beetje ga je veel Spaans spreken."},

 4: {
  "titulo": "Mi familia", "lugar": "En casa · mirando una foto",
  "tu": "Tú", "otro": "Josefina", "otro_avatar": "👨‍👩‍👧",
  "mision": "Toon een foto en zeg wie er op staat en hoe ze zijn.",
  "mision_es": "Enseña una foto: quién es y cómo es.",
  "pasos": [
   {"di": "¿Y esta foto? ¿Quién es?", "nl": "En deze foto? Wie is dat?",
    "meta": "Zeg dat het je moeder is.",
    "hueco": {"marco": "___ es ___ madre.", "respuestas": [["esta"], ["mi"]],
              "banco": ["esta", "este", "mi", "tu", "su"],
              "mal": ["<i>Madre</i> is vrouwelijk: <b>esta</b>.",
                      "«Mijn» is <b>mi</b>."]},
    "opciones": [("Esta es mi madre.", True, None),
                 ("Este es mi madre.", False, "<i>Madre</i> is vrouwelijk: <b>esta</b>.")],
    "acepta": [r"est[ae]\s+es\s+mi\s+\w+", r"es\s+mi\s+\w+"],
    "pista": "«Esta es mi …» (vrouw) of «Este es mi …» (man).",
    "modelo": "Esta es mi madre."},
   {"di": "¡Qué guapa! ¿Y cómo es?", "nl": "Wat knap! En hoe is ze?",
    "meta": "Beschrijf haar met twee woorden.",
    "hueco": {"marco": "Es ___ y muy ___.", "respuestas": [["alta"], ["simpática", "simpatica"]],
              "banco": ["alta", "alto", "simpática", "simpático", "guapa"],
              "mal": ["Ze is een vrouw: <b>alta</b>.", "En dus ook <b>simpática</b>."]},
    "opciones": [("Es alta y muy simpática.", True, None),
                 ("Es alto y muy simpático.", False,
                  "Over een vrouw: <b>alta</b> en <b>simpática</b>.")],
    "acepta": [r"es\s+\w+", r"(alta|baja|guapa|simp[aá]tica|morena|rubia)"],
    "pista": "«Es + hoe ze is». Over een vrouw eindigt het vaak op -a.",
    "modelo": "Es alta y muy simpática."},
   {"di": "¿Y tienes hermanos?", "nl": "En heb je broers of zussen?",
    "meta": "Zeg hoeveel je er hebt.",
    "hueco": {"marco": "___ un ___.", "respuestas": [["tengo"], ["hermano"]],
              "banco": ["tengo", "soy", "hermano", "hermana", "padre"],
              "mal": ["Bezit gaat met <b>tengo</b>.", "Een broer is <b>el hermano</b>."]},
    "opciones": [("Tengo un hermano.", True, None),
                 ("Soy un hermano.", False, "«Ik heb» is <b>tengo</b>.")],
    "acepta": [r"tengo\s+(un|una|dos|tres)?\s*herman", r"no\s+tengo"],
    "pista": "«Tengo un hermano / una hermana».", "modelo": "Tengo un hermano."}],
  "final": "¡Qué familia tan bonita!", "final_nl": "Wat een mooie familie!"},

 5: {
  "titulo": "¿Qué es esto?", "lugar": "La academia · en clase",
  "tu": "Tú", "otro": "Julio", "otro_avatar": "🪑",
  "mision": "Benoem twee voorwerpen en zeg waarvoor er één dient.",
  "mision_es": "Di qué es y para qué sirve.",
  "pasos": [
   {"di": "A ver, ¿qué es esto?", "nl": "Kijk eens, wat is dit?",
    "meta": "Zeg dat het een stoel is.",
    "hueco": {"marco": "Esto ___ ___ silla.", "respuestas": [["es"], ["una"]],
              "banco": ["es", "son", "una", "un", "la"],
              "mal": ["Eén ding: <b>es</b>.", "<i>Silla</i> is vrouwelijk: <b>una</b>."]},
    "opciones": [("Esto es una silla.", True, None),
                 ("Esto es un silla.", False, "<i>Silla</i> is vrouwelijk: <b>una</b>.")],
    "acepta": [r"esto\s+es\s+(un|una)\s+\w+", r"es\s+(un|una)\s+\w+"],
    "pista": "«Esto es un/una …».", "modelo": "Esto es una silla."},
   {"di": "Muy bien. ¿Y para qué sirve?", "nl": "Heel goed. En waarvoor dient ze?",
    "meta": "Zeg waarvoor ze dient.",
    "hueco": {"marco": "___ ___ descansar.", "respuestas": [["sirve"], ["para"]],
              "banco": ["sirve", "sirven", "para", "por", "de"],
              "mal": ["Eén ding: <b>sirve</b>.", "Een doel krijgt <b>para</b>."]},
    "opciones": [("Sirve para descansar.", True, None),
                 ("Sirve por descansar.", False, "Een doel krijgt <b>para</b>.")],
    "acepta": [r"sirve\s+para\s+\w+", r"para\s+\w+ar\b"],
    "pista": "«Sirve para + hele werkwoord».", "modelo": "Sirve para descansar."},
   {"di": "¿Y hay un ordenador en la clase?", "nl": "En is er een computer in de klas?",
    "meta": "Zeg dat er twee zijn.",
    "hueco": {"marco": "Sí, ___ ___ ordenadores.", "respuestas": [["hay"], ["dos"]],
              "banco": ["hay", "son", "está", "dos", "un"],
              "mal": ["«Er is / er zijn» is altijd <b>hay</b>.",
                      "Een aantal: <b>dos</b>."]},
    "opciones": [("Sí, hay dos ordenadores.", True, None),
                 ("Sí, son dos ordenadores.", False,
                  "Om te zeggen dát er iets is: <b>hay</b>.")],
    "acepta": [r"\bhay\b"],
    "pista": "«Hay + aantal + ding».", "modelo": "Sí, hay dos ordenadores."}],
  "final": "¡Perfecto! Ya sabes decir qué hay en la clase.",
  "final_nl": "Perfect! Nu kan je zeggen wat er in de klas is."},

 6: {
  "titulo": "¿Dónde está?", "lugar": "En casa · buscando las llaves",
  "tu": "Tú", "otro": "María", "otro_avatar": "🔑",
  "mision": "Zeg waar iets ligt en vraag toestemming voor iets.",
  "mision_es": "Di dónde está algo y pide permiso.",
  "pasos": [
   {"di": "¿Dónde están mis llaves?", "nl": "Waar zijn mijn sleutels?",
    "meta": "Zeg dat ze op de tafel liggen.",
    "hueco": {"marco": "___ ___ la mesa.", "respuestas": [["encima"], ["de"]],
              "banco": ["encima", "debajo", "de", "en", "al"],
              "mal": ["«Bovenop» is <b>encima</b>.",
                      "Er hoort <b>de</b> achter: «encima <i>de</i> la mesa»."]},
    "opciones": [("Encima de la mesa.", True, None),
                 ("Debajo de la mesa.", False,
                  "<i>Debajo</i> is eronder. Bovenop is <b>encima</b>.")],
    "acepta": [r"(encima|debajo|al\s+lado|dentro|delante|detr[aá]s)\s*(de)?"],
    "pista": "encima de · debajo de · al lado de · dentro de.",
    "modelo": "Encima de la mesa."},
   {"di": "¡Ah, gracias! ¿Y mi móvil?", "nl": "Ah, dank je! En mijn gsm?",
    "meta": "Zeg dat hij in de keuken ligt.",
    "hueco": {"marco": "___ ___ la cocina.", "respuestas": [["está", "esta"], ["en"]],
              "banco": ["está", "es", "hay", "en", "a"],
              "mal": ["Waar iets ligt: <b>está</b>.", "En met <b>en</b>: «en la cocina»."]},
    "opciones": [("Está en la cocina.", True, None),
                 ("Es en la cocina.", False, "Waar iets is, gaat met <b>está</b>.")],
    "acepta": [r"est[aá]\s+en\s+\w+"],
    "pista": "«Está en …».", "modelo": "Está en la cocina."},
   {"di": "Perfecto. Voy a salir.", "nl": "Perfect. Ik ga weg.",
    "meta": "Vraag of je mee mag.",
    "hueco": {"marco": "¿___ ___ contigo?", "respuestas": [["puedo"], ["ir"]],
              "banco": ["puedo", "puedes", "ir", "voy", "vas"],
              "mal": ["Bij <i>yo</i>: <b>puedo</b>.",
                      "Na <i>puedo</i> komt het hele werkwoord: <b>ir</b>."]},
    "opciones": [("¿Puedo ir contigo?", True, None),
                 ("¿Puedo voy contigo?", False,
                  "Na <i>puedo</i> komt het hele werkwoord: <b>ir</b>.")],
    "acepta": [r"puedo\s+\w+"],
    "pista": "«¿Puedo + hele werkwoord?»", "modelo": "¿Puedo ir contigo?"}],
  "final": "¡Claro que sí! Vamos.", "final_nl": "Natuurlijk! Kom mee."},

 7: {
  "titulo": "¿A qué te dedicas?", "lugar": "En una fiesta · alguien nuevo",
  "tu": "Tú", "otro": "El invitado", "otro_avatar": "💼",
  "mision": "Vraag naar iemands beroep en zeg wat jij doet.",
  "mision_es": "Pregunta por la profesión y di la tuya.",
  "pasos": [
   {"di": "Hola. Yo trabajo en una tienda. ¿Y tú?", "nl": "Hallo. Ik werk in een winkel. En jij?",
    "meta": "Zeg dat je student bent.",
    "hueco": {"marco": "___ ___.", "respuestas": [["soy"], ["estudiante"]],
              "banco": ["soy", "estoy", "estudiante", "profesor", "trabajo"],
              "mal": ["Een beroep krijgt <b>ser</b>: «soy…».",
                      "Het woord is <b>estudiante</b>."]},
    "opciones": [("Soy estudiante.", True, None),
                 ("Soy un estudiante.", False,
                  "Bij een beroep valt <i>un/una</i> weg: <b>soy estudiante</b>.")],
    "acepta": [r"soy\s+\w+", r"estudio\s+\w+"],
    "pista": "«Soy estudiante» — zonder <i>un</i>.", "modelo": "Soy estudiante."},
   {"di": "¡Qué bien! ¿Y qué estudias?", "nl": "Wat goed! En wat studeer je?",
    "meta": "Vraag hém wat hij precies doet.",
    "hueco": {"marco": "¿___ ___ trabajas?", "respuestas": [["en"], ["qué", "que"]],
              "banco": ["en", "a", "qué", "cómo", "dónde"],
              "mal": ["De vaste vraag is «¿<b>en</b> qué trabajas?»",
                      "En met <b>qué</b>, met accent."]},
    "opciones": [("¿En qué trabajas?", True, None),
                 ("¿A qué trabajas?", False,
                  "De vaste vraag is <b>¿en qué trabajas?</b> of <b>¿a qué te dedicas?</b>")],
    "acepta": [r"en\s+qu[eé]\s+trabajas", r"a\s+qu[eé]\s+te\s+dedicas"],
    "pista": "«¿En qué trabajas?» of «¿A qué te dedicas?»",
    "modelo": "¿En qué trabajas?"},
   {"di": "Soy profesor de música.", "nl": "Ik ben muziekleraar.",
    "meta": "Reageer verrast en positief.",
    "hueco": {"marco": "¡___ ___!", "respuestas": [["qué", "que"], ["interesante", "bien", "guay"]],
              "banco": ["qué", "cómo", "interesante", "bien", "mal"],
              "mal": ["Een uitroep begint met <b>qué</b>.",
                      "Iets positiefs: interesante · bien · guay."]},
    "opciones": [("¡Qué interesante!", True, None),
                 ("¡Cómo interesante!", False, "Een uitroep begint met <b>qué</b>.")],
    "acepta": [r"qu[eé]\s+(interesante|bien|guay|bonito)"],
    "pista": "«¡Qué …!» + een positief woord.", "modelo": "¡Qué interesante!"}],
  "final": "Gracias. Oye, ¿quieres tomar algo?",
  "final_nl": "Dank je. Zeg, wil je iets drinken?"},

 8: {
  "titulo": "¿Qué hora es?", "lugar": "Por teléfono · esta noche",
  "tu": "Tú", "otro": "Julio", "otro_avatar": "🕗",
  "mision": "Zeg hoe laat het is en spreek een uur af.",
  "mision_es": "Di la hora y queda a una hora.",
  "pasos": [
   {"di": "Oye, ¿qué hora es?", "nl": "Zeg, hoe laat is het?",
    "meta": "Zeg dat het half negen is.",
    "hueco": {"marco": "___ las ocho ___ media.", "respuestas": [["son"], ["y"]],
              "banco": ["son", "es", "y", "menos", "en"],
              "mal": ["Vanaf twee uur: <b>son</b> las…", "Half = <b>y</b> media."]},
    "opciones": [("Son las ocho y media.", True, None),
                 ("Es las ocho y media.", False,
                  "Alleen bij één uur zeg je <i>es la una</i>. Verder: <b>son las</b>.")],
    "acepta": [r"son\s+las\s+\w+", r"es\s+la\s+una"],
    "pista": "«Son las …» + y media / y cuarto / menos cuarto.",
    "modelo": "Son las ocho y media."},
   {"di": "¿Quieres quedar esta noche?", "nl": "Wil je vanavond afspreken?",
    "meta": "Zeg ja en vraag hoe laat.",
    "hueco": {"marco": "¡Vale! ¿___ ___ hora?", "respuestas": [["a"], ["qué", "que"]],
              "banco": ["a", "en", "qué", "cómo", "cuál"],
              "mal": ["Een uur krijgt <b>a</b>.", "En dan <b>qué</b>: «¿a qué hora?»"]},
    "opciones": [("¡Vale! ¿A qué hora?", True, None),
                 ("¡Vale! ¿En qué hora?", False, "Het is <b>¿a qué hora?</b>")],
    "acepta": [r"a\s+qu[eé]\s+hora", r"vale"],
    "pista": "«Vale» + «¿A qué hora?»", "modelo": "¡Vale! ¿A qué hora?"},
   {"di": "¿A las diez en mi casa?", "nl": "Om tien uur bij mij thuis?",
    "meta": "Bevestig en zeg tot straks.",
    "hueco": {"marco": "Perfecto. ___ ___ ahora.", "respuestas": [["hasta"], ["ahora"]],
              "banco": ["hasta", "adiós", "ahora", "luego", "mañana"],
              "mal": ["«Tot» is <b>hasta</b>.",
                      "«Tot zo» is hasta <b>ahora</b> — je ziet elkaar nog vandaag."]},
    "opciones": [("Perfecto. Hasta ahora.", True, None),
                 ("Perfecto. Hasta mañana.", False,
                  "Jullie zien elkaar vanavond nog: <b>hasta ahora</b> of <b>hasta luego</b>.")],
    "acepta": [r"hasta\s+(ahora|luego)", r"perfecto|vale"],
    "pista": "«Hasta ahora» als je elkaar straks ziet.",
    "modelo": "Perfecto. Hasta ahora."}],
  "final": "¡Genial! Te veo en veinte minutos.",
  "final_nl": "Top! Ik zie je over twintig minuten."},

 9: {
  "titulo": "¿Qué vas a hacer?", "lugar": "El viernes · en el pasillo",
  "tu": "Tú", "otro": "María", "otro_avatar": "📅",
  "mision": "Vertel je plannen en zeg wat je eerst moet doen.",
  "mision_es": "Habla de tus planes y de lo que tienes que hacer.",
  "pasos": [
   {"di": "¿Qué vas a hacer este fin de semana?", "nl": "Wat ga je dit weekend doen?",
    "meta": "Zeg wat je van plan bent.",
    "hueco": {"marco": "___ ___ ver una película.", "respuestas": [["voy"], ["a"]],
              "banco": ["voy", "vas", "a", "de", "que"],
              "mal": ["Bij <i>yo</i>: <b>voy</b>.",
                      "Een plan is <b>voy a</b> + hele werkwoord."]},
    "opciones": [("Voy a ver una película.", True, None),
                 ("Voy ver una película.", False,
                  "Er hoort een <b>a</b> tussen: «voy <i>a</i> ver».")],
    "acepta": [r"voy\s+a\s+\w+"],
    "pista": "«Voy a + hele werkwoord».", "modelo": "Voy a ver una película."},
   {"di": "¡Qué bien! ¿Y hoy?", "nl": "Wat leuk! En vandaag?",
    "meta": "Zeg wat je vandaag moet doen.",
    "hueco": {"marco": "Hoy ___ ___ estudiar.", "respuestas": [["tengo"], ["que"]],
              "banco": ["tengo", "voy", "que", "de", "a"],
              "mal": ["«Ik moet» begint met <b>tengo</b>.",
                      "De vaste combinatie is <b>tener que</b>."]},
    "opciones": [("Hoy tengo que estudiar.", True, None),
                 ("Hoy tengo de estudiar.", False, "Het is <b>tengo que</b>.")],
    "acepta": [r"tengo\s+que\s+\w+"],
    "pista": "«Tengo que + hele werkwoord».", "modelo": "Hoy tengo que estudiar."},
   {"di": "¿Quedamos mañana entonces?", "nl": "Spreken we morgen dan af?",
    "meta": "Zeg ja en stel een moment voor.",
    "hueco": {"marco": "Sí, ___ la ___.", "respuestas": [["por"], ["tarde"]],
              "banco": ["por", "en", "a", "tarde", "mañana"],
              "mal": ["Een dagdeel krijgt <b>por</b>: «por la tarde».",
                      "«De namiddag» is <b>la tarde</b>."]},
    "opciones": [("Sí, por la tarde.", True, None),
                 ("Sí, en la tarde.", False,
                  "In Spanje zegt men <b>por la tarde</b>.")],
    "acepta": [r"por\s+la\s+(ma[ñn]ana|tarde|noche)", r"s[ií]"],
    "pista": "por la mañana · por la tarde · por la noche.",
    "modelo": "Sí, por la tarde."}],
  "final": "¡Perfecto! Te escribo mañana.",
  "final_nl": "Perfect! Ik schrijf je morgen."},

 10: {
  "titulo": "¿Te ayudo?", "lugar": "En casa · hay que limpiar",
  "tu": "Tú", "otro": "Josefina", "otro_avatar": "🧹",
  "mision": "Bied hulp aan, zeg wat je kan en vraag wat je moet doen.",
  "mision_es": "Ofrece ayuda, di qué sabes hacer y pregunta qué hacer.",
  "pasos": [
   {"di": "¡Uf! Hay que limpiar toda la casa.", "nl": "Oef! Het hele huis moet gepoetst worden.",
    "meta": "Bied je hulp aan.",
    "hueco": {"marco": "___ ___ ayudo.", "respuestas": [["yo"], ["te"]],
              "banco": ["yo", "tú", "te", "me", "le"],
              "mal": ["Begin met <b>yo</b> om jezelf te benadrukken.",
                      "«Ik help jou» is yo <b>te</b> ayudo."]},
    "opciones": [("Yo te ayudo.", True, None),
                 ("Yo me ayudo.", False, "Dan help je jezelf. Aan haar: <b>te</b> ayudo.")],
    "acepta": [r"(yo\s+)?te\s+ayudo", r"te\s+ayudo"],
    "pista": "«Yo te ayudo» of «¿Te ayudo?»", "modelo": "Yo te ayudo."},
   {"di": "¿De verdad? ¿Y sabes pasar la aspiradora?", "nl": "Echt? En kan je stofzuigen?",
    "meta": "Zeg dat je het kan.",
    "hueco": {"marco": "Claro que ___ ___ hacerlo.", "respuestas": [["sé", "se"], ["sé", "se"]],
              "banco": ["sé", "sabes", "puedo", "hacer", "tengo"],
              "mal": ["«Ik kan» (heb geleerd) is <b>sé</b>.",
                      "Herhaal <b>sé</b>, of schrijf <i>puedo</i>."]},
    "opciones": [("Claro que sé hacerlo.", True, None),
                 ("Claro que sabes hacerlo.", False,
                  "Bij <i>yo</i>: <b>sé</b>. <i>Sabes</i> gaat over jou.")],
    "acepta": [r"\bs[eé]\b", r"claro\s+que"],
    "pista": "«Sé + hele werkwoord» = ik kan het (ik heb het geleerd).",
    "modelo": "Claro que sé hacerlo."},
   {"di": "¡Estupendo! Pues empieza tú.", "nl": "Prima! Begin jij dan maar.",
    "meta": "Vraag wat je precies moet doen.",
    "hueco": {"marco": "¿Qué ___ ___ hacer?", "respuestas": [["tengo"], ["que"]],
              "banco": ["tengo", "voy", "que", "de", "a"],
              "mal": ["«Ik moet» begint met <b>tengo</b>.",
                      "En dan <b>que</b>: «tengo que hacer»."]},
    "opciones": [("¿Qué tengo que hacer?", True, None),
                 ("¿Qué tengo de hacer?", False, "Het is <b>tengo que</b>.")],
    "acepta": [r"qu[eé]\s+tengo\s+que\s+hacer", r"tengo\s+que"],
    "pista": "«¿Qué tengo que hacer?»", "modelo": "¿Qué tengo que hacer?"}],
  "final": "Primero el salón. ¡Y gracias, eh!",
  "final_nl": "Eerst de woonkamer. En bedankt, hè!"},

 11: {
  "titulo": "¿Qué tiempo hace?", "lugar": "En el bar · hablando de las vacaciones",
  "tu": "Tú", "otro": "El camarero", "otro_avatar": "☕",
  "mision": "Praat over het weer en over wat je graag doet in de vakantie.",
  "mision_es": "Habla del tiempo y de lo que te gusta hacer.",
  "pasos": [
   {"di": "¿Adónde vas de vacaciones?", "nl": "Waar ga je heen op vakantie?",
    "meta": "Zeg waar je heen gaat en hoe.",
    "hueco": {"marco": "___ ___ la playa, en avión.", "respuestas": [["voy"], ["a"]],
              "banco": ["voy", "vas", "a", "en", "de"],
              "mal": ["Bij <i>yo</i>: <b>voy</b>.", "Na <i>ir</i> hoort <b>a</b>."]},
    "opciones": [("Voy a la playa, en avión.", True, None),
                 ("Voy la playa, en avión.", False, "Na <i>voy</i> hoort <b>a</b>.")],
    "acepta": [r"voy\s+a\s+\w+"],
    "pista": "«Voy a + plaats» + «en avión / en tren / en coche».",
    "modelo": "Voy a la playa, en avión."},
   {"di": "¡Qué bien! Allí siempre hace buen tiempo.", "nl": "Wat goed! Daar is het altijd mooi weer.",
    "meta": "Zeg wat voor weer het hier vandaag is.",
    "hueco": {"marco": "Aquí hoy ___ ___.", "respuestas": [["hace"], ["frío", "frio", "calor", "sol", "viento"]],
              "banco": ["hace", "está", "tengo", "frío", "sol"],
              "mal": ["Het weer krijgt <b>hace</b>.",
                      "Kies: frío · calor · sol · viento."]},
    "opciones": [("Aquí hoy hace frío.", True, None),
                 ("Aquí hoy tengo frío.", False,
                  "<i>Tengo frío</i> gaat over jóú. Over het weer: <b>hace frío</b>."),
                 ("Aquí hoy está frío.", False,
                  "Het weer krijgt <b>hacer</b>: «hace frío».")],
    "acepta": [r"hace\s+(fr[ií]o|calor|sol|viento|buen|mal)", r"(llueve|nieva)"],
    "pista": "«Hace + frío/calor/sol/viento» — of «llueve».",
    "modelo": "Aquí hoy hace frío."},
   {"di": "Sí… ¿Y a ti qué te gusta hacer?", "nl": "Ja… En wat doe jij graag?",
    "meta": "Zeg wat je graag doet.",
    "hueco": {"marco": "___ ___ nadar.", "respuestas": [["me"], ["gusta"]],
              "banco": ["me", "yo", "gusta", "gustan", "gusto"],
              "mal": ["Het is <b>me</b> gusta.",
                      "Bij een werkwoord blijft het <b>gusta</b>, enkelvoud."]},
    "opciones": [("Me gusta nadar.", True, None),
                 ("Yo gusto nadar.", False, "Nooit «yo gusto». Het is <b>me gusta</b>.")],
    "acepta": [r"me\s+(gusta|encanta)\s+\w+"],
    "pista": "«Me gusta + hele werkwoord».", "modelo": "Me gusta nadar."}],
  "final": "A mí también. ¡Buen viaje!", "final_nl": "Ik ook. Goede reis!"},

 12: {
  "titulo": "¿Qué llevas hoy?", "lugar": "La academia · la clase de Julio",
  "tu": "Tú", "otro": "Julio", "otro_avatar": "👕",
  "mision": "Beschrijf wat iemand aanheeft en vertel iets over je ochtend.",
  "mision_es": "Di qué lleva alguien y cuenta tu rutina.",
  "pasos": [
   {"di": "Mira a Paul. ¿Qué lleva hoy?", "nl": "Kijk naar Paul. Wat heeft hij vandaag aan?",
    "meta": "Zeg wat hij draagt, met de kleur erbij.",
    "hueco": {"marco": "___ una chaqueta ___.", "respuestas": [["lleva"], ["negra"]],
              "banco": ["lleva", "llevo", "tiene", "negra", "negro"],
              "mal": ["Wat iemand aanheeft: <b>lleva</b>.",
                      "<i>Chaqueta</i> is vrouwelijk: <b>negra</b>."]},
    "opciones": [("Lleva una chaqueta negra.", True, None),
                 ("Lleva una chaqueta negro.", False,
                  "De kleur past zich aan: <b>negra</b> bij <i>chaqueta</i>."),
                 ("Tiene una chaqueta negra.", False,
                  "<i>Tener</i> is bezitten. Wat hij nú aanheeft: <b>lleva</b>.")],
    "acepta": [r"lleva\s+(un|una|unos|unas)\s+\w+"],
    "pista": "«Lleva + kledingstuk + kleur».", "modelo": "Lleva una chaqueta negra."},
   {"di": "Muy bien. ¿Y cómo es Paul?", "nl": "Heel goed. En hoe is Paul?",
    "meta": "Beschrijf hem met twee dingen.",
    "hueco": {"marco": "___ alto y ___ los ojos azules.",
              "respuestas": [["es"], ["tiene"]],
              "banco": ["es", "está", "tiene", "lleva", "hay"],
              "mal": ["Hoe hij áltijd is: <b>es</b> alto.",
                      "Lichaamskenmerken krijgen <b>tiene</b>: «tiene los ojos azules»."]},
    "opciones": [("Es alto y tiene los ojos azules.", True, None),
                 ("Está alto y lleva los ojos azules.", False,
                  "Zijn lengte is blijvend: <b>es alto</b>. En ogen: <b>tiene</b>.")],
    "acepta": [r"es\s+\w+", r"tiene\s+(el|los|las|la)\s+\w+"],
    "pista": "«Es + hoe hij is» en «Tiene + lichaamskenmerk».",
    "modelo": "Es alto y tiene los ojos azules."},
   {"di": "¿Y tú? ¿Qué haces por las mañanas?", "nl": "En jij? Wat doe je 's ochtends?",
    "meta": "Vertel wat je elke ochtend doet.",
    "hueco": {"marco": "___ ___ y me peino.", "respuestas": [["me"], ["ducho"]],
              "banco": ["me", "yo", "ducho", "duchas", "peino"],
              "mal": ["Wederkerend: <b>me</b> ducho.", "Bij <i>yo</i>: <b>ducho</b>."]},
    "opciones": [("Me ducho y me peino.", True, None),
                 ("Yo ducho y peino.", False,
                  "Allebei wederkerend: <b>me ducho</b> en <b>me peino</b>.")],
    "acepta": [r"me\s+(ducho|peino|levanto|visto|afeito)"],
    "pista": "«Me ducho · me peino · me levanto».", "modelo": "Me ducho y me peino."}],
  "final": "¡Muy bien! Ya sabes describir a una persona.",
  "final_nl": "Heel goed! Nu kan je iemand beschrijven."},

 13: {
  "titulo": "En el mercado", "lugar": "El mercado · el puesto de fruta",
  "tu": "Tú", "otro": "La vendedora", "otro_avatar": "🍎",
  "mision": "Koop fruit: vraag de prijs, zeg hoeveel je wil, en zeg waarom je "
            "iets niet koopt.",
  "mision_es": "Compra fruta: precio, cantidad y una razón.",
  "pasos": [
   {"di": "¡Buenos días! ¿Qué le pongo?", "nl": "Goedemorgen! Wat mag het zijn?",
    "meta": "Vraag hoeveel de appels kosten.",
    "hueco": {"marco": "¿___ ___ las manzanas?",
              "respuestas": [["cuánto", "cuanto"], ["cuestan"]],
              "banco": ["cuánto", "cómo", "cuestan", "cuesta", "vale"],
              "mal": ["Naar een prijs vraag je met <b>cuánto</b>.",
                      "Meervoud <i>las manzanas</i> → <b>cuestan</b>."]},
    "opciones": [("¿Cuánto cuestan las manzanas?", True, None),
                 ("¿Cuánto cuesta las manzanas?", False,
                  "Meervoud: <b>cuestan</b>, met -n.")],
    "acepta": [r"cu[aá]nto\s+cuestan?", r"cu[aá]nto\s+es"],
    "pista": "«¿Cuánto cuesta …?» (één ding) · «¿Cuánto cuestan …?» (meerdere).",
    "modelo": "¿Cuánto cuestan las manzanas?"},
   {"di": "Un euro con ochenta el kilo. Están muy buenas.",
    "nl": "Een euro tachtig de kilo. Ze zijn heel lekker.",
    "meta": "Vraag één kilo.",
    "hueco": {"marco": "___ ___ kilo, por favor.", "respuestas": [["un"], ["kilo"]],
              "banco": ["un", "una", "kilo", "medio", "litro"],
              "mal": ["<i>Kilo</i> is mannelijk: <b>un</b> kilo.",
                      "Het woord is <b>kilo</b>."]},
    "opciones": [("Un kilo, por favor.", True, None),
                 ("Una kilo, por favor.", False, "<i>Kilo</i> is mannelijk: <b>un</b>.")],
    "acepta": [r"(un|medio)\s+kilo", r"por\s+favor"],
    "pista": "«Un kilo, por favor» of «Medio kilo».", "modelo": "Un kilo, por favor."},
   {"di": "Aquí tiene. ¿Y unos tomates?", "nl": "Alstublieft. En wat tomaten?",
    "meta": "Zeg nee en geef de reden.",
    "hueco": {"marco": "No, gracias, ___ ___ me gustan.",
              "respuestas": [["porque"], ["no"]],
              "banco": ["porque", "por qué", "no", "sí", "nunca"],
              "mal": ["De reden begint met <b>porque</b>, aan elkaar.",
                      "De ontkenning staat vóór het werkwoord: <b>no</b> me gustan."]},
    "opciones": [("No, gracias, porque no me gustan.", True, None),
                 ("No, gracias, por qué no me gustan.", False,
                  "<b>Porque</b> aan elkaar is het antwoord; <i>por qué</i> is de vraag.")],
    "acepta": [r"porque\s+\w+", r"no,?\s*gracias"],
    "pista": "«No, gracias, porque …».", "modelo": "No, gracias, porque no me gustan."}],
  "final": "Sin problema. Son un euro ochenta. ¡Hasta la próxima!",
  "final_nl": "Geen probleem. Dat is een euro tachtig. Tot de volgende keer!"},

 14: {
  "titulo": "En el restaurante", "lugar": "Un restaurante · con la familia",
  "tu": "Tú", "otro": "El camarero", "otro_avatar": "🍽️",
  "mision": "Bestel iets te drinken en een gerecht, en reageer op het eten.",
  "mision_es": "Pide bebida y comida, y valora el plato.",
  "pasos": [
   {"di": "Buenas noches. ¿Quieren algo de beber?", "nl": "Goedenavond. Wilt u iets drinken?",
    "meta": "Bestel water.",
    "hueco": {"marco": "___ ___ agua, por favor.", "respuestas": [["una"], ["botella"]],
              "banco": ["una", "un", "botella", "vaso", "plato"],
              "mal": ["<i>Botella</i> is vrouwelijk: <b>una</b>.",
                      "Een fles is <b>una botella de</b>."]},
    "opciones": [("Una botella de agua, por favor.", True, None),
                 ("Un botella de agua, por favor.", False,
                  "<i>Botella</i> is vrouwelijk: <b>una</b>.")],
    "acepta": [r"(una\s+botella|un\s+vaso|agua|cerveza|refresco)", r"por\s+favor"],
    "pista": "«Una botella de agua, por favor».",
    "modelo": "Una botella de agua, por favor."},
   {"di": "Muy bien. De segundo les recomiendo la paella.",
    "nl": "Heel goed. Als hoofdgerecht raad ik u de paella aan.",
    "meta": "Bestel de paella.",
    "hueco": {"marco": "___ ___, la paella.", "respuestas": [["para"], ["mí", "mi"]],
              "banco": ["para", "por", "mí", "yo", "me"],
              "mal": ["De uitdrukking is <b>para mí</b>.",
                      "Na <i>para</i> wordt <i>yo</i> → <b>mí</b>."]},
    "opciones": [("Para mí, la paella.", True, None),
                 ("Para yo, la paella.", False,
                  "Na een voorzetsel wordt het <b>mí</b>: «para mí».")],
    "acepta": [r"para\s+m[ií]", r"(quiero|yo\s+quiero)\s+\w+"],
    "pista": "«Para mí, …» of «Yo quiero …».", "modelo": "Para mí, la paella."},
   {"di": "¿Qué tal está todo?", "nl": "Hoe is alles?",
    "meta": "Zeg dat het heel lekker is.",
    "hueco": {"marco": "___ ___, gracias.", "respuestas": [["está", "esta"], ["buenísima", "buenisima", "muy buena", "rica"]],
              "banco": ["está", "es", "buenísima", "buenísimo", "rica"],
              "mal": ["Hoe iets nú smaakt: <b>está</b>.",
                      "<i>La paella</i> is vrouwelijk: <b>buenísima</b> of <b>rica</b>."]},
    "opciones": [("Está buenísima, gracias.", True, None),
                 ("Es buenísimo, gracias.", False,
                  "Over <i>la paella</i>: <b>está buenísima</b> — vrouwelijk, en met <i>estar</i>.")],
    "acepta": [r"est[aá]\s+(buen[ií]sim|muy\s+buena|rica|riqu[ií]sim)", r"qu[eé]\s+ric"],
    "pista": "«Está buenísima» of «¡Qué rica!»", "modelo": "Está buenísima, gracias."}],
  "final": "¡Me alegro! ¿Van a tomar postre?",
  "final_nl": "Dat doet me plezier! Neemt u nog een nagerecht?"},
}
