#!/usr/bin/env python3
"""De rollenspellen van C6+ «Más español en la práctica · edición única».

Zelfde vorm als C5 (zie de kop van `rol_data.py`), maar zwaarder: hier komen
het verleden, por/para, de vergelijking, de gebiedende wijs en de eigen mening
aan bod. De scènes vragen dus niet alleen een bestelling maar een verhaal — en
dat is precies waar deze cursus naartoe werkt.

DE SCÈNE MOET DE GRAMMATICA VAN HAAR UNIT UITLOKKEN
Bij een unit over het imperfecto helpt het niet om naar de weg te vragen: dan
komt de vorm niet voor. De opdracht is daarom telkens zo gekozen dat de
leerling de nieuwe vorm wel móet gebruiken — over vroeger vertellen, twee
dingen vergelijken, een raad geven, een mening verdedigen.
"""

ROLES = {
 # ── U0 · ¡Volvemos! · terug na de zomer ───────────────────────────────────
 0: {
  "titulo": "De vuelta en clase",
  "lugar": "El primer día del curso · el pasillo del instituto",
  "tu": "Tú",
  "otro": "Mateo",
  "otro_avatar": "🎒",
  "mision": "Je ziet een klasgenoot terug na de vakantie. Groet, stel jezelf "
            "opnieuw voor aan de nieuwe leerling, en vertel kort hoe het gaat.",
  "mision_es": "Saluda, preséntate y cuenta qué tal estás.",
  "pasos": [
   {"di": "¡Hombre, cuánto tiempo! ¿Qué tal el verano?",
    "nl": "Hé, dat is lang geleden! Hoe was de zomer?",
    "meta": "Zeg dat het goed was en vraag terug.",
    "hueco": {"marco": "¡Muy bien, gracias! ¿___ ___?",
              "respuestas": [["y"], ["tú", "tu"]],
              "banco": ["y", "o", "tú", "te", "usted"],
              "mal": ["De korte tegenvraag begint met <b>y</b>: «¿Y tú?»",
                      "Tegen een klasgenoot: <b>tú</b>, met accent."]},
    "opciones": [
      ("¡Muy bien, gracias! ¿Y tú?", True, None),
      ("¡Muy bien, gracias! ¿Y usted?", False,
       "<i>Usted</i> is voor volwassen vreemden. Tegen een klasgenoot: <b>tú</b>."),
    ],
    "acepta": [r"(muy\s+)?bien", r"y\s+t[uú]"],
    "pista": "«Muy bien, gracias» en dan de tegenvraag «¿Y tú?».",
    "modelo": "¡Muy bien, gracias! ¿Y tú?"},

   {"di": "Genial. Mira, esta es Nadia, es nueva. Nadia, este es un compañero de clase.",
    "nl": "Top. Kijk, dit is Nadia, ze is nieuw. Nadia, dit is een klasgenoot.",
    "meta": "Stel jezelf voor aan Nadia: naam en waar je woont.",
    "hueco": {"marco": "Hola, Nadia. ___ ___ Lars y vivo en Gante.",
              "respuestas": [["me"], ["llamo"]],
              "banco": ["me", "yo", "llamo", "llamas", "soy"],
              "mal": ["Wederkerend: <b>me</b> llamo.",
                      "Bij <i>yo</i>: <b>llamo</b>."]},
    "opciones": [
      ("Hola, Nadia. Me llamo Lars y vivo en Gante.", True, None),
      ("Hola, Nadia. Me llamo Lars y soy en Gante.", False,
       "«Ik woon in» is <b>vivo en</b>. <i>Soy de</i> zou je herkomst zijn."),
    ],
    "acepta": [r"me\s+llamo\s+\w+", r"(yo\s+)?soy\s+\w+"],
    "pista": "«Me llamo …» + «vivo en …».",
    "modelo": "Hola, Nadia. Me llamo Lars y vivo en Gante."},

   {"di": "Encantada. ¿Y de dónde eres exactamente?",
    "nl": "Aangenaam. En waar kom je precies vandaan?",
    "meta": "Zeg je herkomst én je nationaliteit.",
    "hueco": {"marco": "___ de Bélgica, ___ belga.",
              "respuestas": [["soy"], ["soy"]],
              "banco": ["soy", "estoy", "tengo", "vivo", "es"],
              "mal": ["Herkomst gaat met <b>ser</b>: «soy de…».",
                      "Ook nationaliteit gaat met <b>ser</b>: «soy belga»."]},
    "opciones": [
      ("Soy de Bélgica, soy belga.", True, None),
      ("Estoy de Bélgica, soy belga.", False,
       "Herkomst krijgt <b>ser</b>: «soy de Bélgica»."),
    ],
    "acepta": [r"soy\s+de\s+\w+", r"soy\s+belga"],
    "pista": "Twee keer <b>ser</b>: «soy de …» en «soy …».",
    "modelo": "Soy de Bélgica, soy belga."},

   {"di": "¿Y cómo eres? Cuéntame algo de ti.",
    "nl": "En hoe ben je? Vertel eens iets over jezelf.",
    "meta": "Beschrijf jezelf met twee eigenschappen.",
    "hueco": {"marco": "___ bastante ___ y me gusta el deporte.",
              "respuestas": [["soy"], ["tranquilo", "tranquila", "simpático", "simpática"]],
              "banco": ["soy", "estoy", "tranquilo", "cansado", "simpático"],
              "mal": ["Hoe je áltijd bent, gaat met <b>ser</b>.",
                      "Kies een karaktereigenschap: tranquilo · simpático · trabajador."]},
    "opciones": [
      ("Soy bastante tranquilo y me gusta el deporte.", True, None),
      ("Estoy bastante tranquilo y me gusta el deporte.", False,
       "<i>Estoy tranquilo</i> = ik ben nú rustig. Voor je karakter: <b>soy</b>."),
    ],
    "acepta": [r"soy\s+(bastante\s+|muy\s+|un\s+poco\s+)?\w+",
               r"me\s+(gusta|encanta)"],
    "pista": "«Soy + eigenschap» en «me gusta + iets».",
    "modelo": "Soy bastante tranquilo y me gusta el deporte."},

   {"di": "Oye, no he entendido tu apellido. ¿Puedes repetirlo?",
    "nl": "Zeg, ik heb je achternaam niet verstaan. Kan je die herhalen?",
    "meta": "Vraag beleefd of ze het trager wil zeggen, en herhaal je naam.",
    "hueco": {"marco": "Claro. ¿Puedes hablar más ___? Me ___ Wansen.",
              "respuestas": [["despacio"], ["llamo"]],
              "banco": ["despacio", "rápido", "llamo", "llamas", "dice"],
              "mal": ["«Trager» is <b>más despacio</b>.",
                      "Bij <i>yo</i>: me <b>llamo</b>."]},
    "opciones": [
      ("Claro. ¿Puedes hablar más despacio? Me llamo Wansen.", True, None),
      ("Claro. ¿Puedes hablar más rápido? Me llamo Wansen.", False,
       "Dan vraag je juist het omgekeerde: <b>más despacio</b> = trager."),
    ],
    "acepta": [r"m[aá]s\s+despacio", r"puedes\s+repetir", r"me\s+llamo"],
    "pista": "Klasuitdrukkingen: ¿puedes repetir? · más despacio, por favor.",
    "modelo": "Claro. ¿Puedes hablar más despacio? Me llamo Wansen."},
  ],
  "final": "¡Ahora sí! Encantada, Lars. Nos vemos en clase de español.",
  "final_nl": "Nu wel! Aangenaam, Lars. Tot in de Spaanse les.",
 },

 # ── U1 · El día a día · rutina + gevoelens ────────────────────────────────
 1: {
  "titulo": "Un día cualquiera",
  "lugar": "En el recreo · con una compañera de intercambio",
  "tu": "Tú",
  "otro": "Alba",
  "otro_avatar": "⏰",
  "mision": "Vertel hoe een gewone dag bij jou verloopt: het uur, de volgorde "
            "en hoe vaak. Zeg ook hoe je je daarbij voelt.",
  "mision_es": "Cuenta tu rutina: la hora, el orden y con qué frecuencia.",
  "pasos": [
   {"di": "En España empezamos a las ocho. ¿A qué hora te levantas tú?",
    "nl": "In Spanje beginnen we om acht uur. Hoe laat sta jij op?",
    "meta": "Zeg hoe laat je opstaat.",
    "hueco": {"marco": "___ ___ a las siete menos cuarto.",
              "respuestas": [["me"], ["levanto"]],
              "banco": ["me", "yo", "levanto", "levantas", "acuesto"],
              "mal": ["Wederkerend werkwoord: <b>me</b> levanto.",
                      "Bij <i>yo</i>: <b>levanto</b>."]},
    "opciones": [
      ("Me levanto a las siete menos cuarto.", True, None),
      ("Me acuesto a las siete menos cuarto.", False,
       "<i>Acostarse</i> is naar bed gaan. Opstaan is <b>levantarse</b>."),
    ],
    "acepta": [r"me\s+(levanto|despierto)", r"a\s+las?\s+\w+"],
    "pista": "«Me levanto a las …» — vergeet <i>me</i> niet.",
    "modelo": "Me levanto a las siete menos cuarto."},

   {"di": "¡Qué pronto! ¿Y qué haces después?",
    "nl": "Wat vroeg! En wat doe je daarna?",
    "meta": "Vertel de volgorde van je ochtend met twee verbindingswoorden.",
    "hueco": {"marco": "___ me ducho y ___ desayuno.",
              "respuestas": [["primero"], ["luego", "después"]],
              "banco": ["primero", "luego", "después", "por último", "antes"],
              "mal": ["Een volgorde begint met <b>primero</b>.",
                      "Daarna komt <b>luego</b> of <b>después</b>."]},
    "opciones": [
      ("Primero me ducho y luego desayuno.", True, None),
      ("Primero me ducho y antes desayuno.", False,
       "<i>Antes</i> betekent «eerder». Voor wat volgt: <b>luego</b> of <b>después</b>."),
    ],
    "acepta": [r"(primero|luego|despu[eé]s|por\s+[uú]ltimo)", r"me\s+ducho|desayuno"],
    "pista": "De ketting: primero · luego · después · por último.",
    "modelo": "Primero me ducho y luego desayuno."},

   {"di": "¿Y comes en el instituto o en casa?",
    "nl": "En eet je op school of thuis?",
    "meta": "Zeg het, en zeg erbij hoe vaak.",
    "hueco": {"marco": "___ ___ como en casa.",
              "respuestas": [["casi"], ["siempre"]],
              "banco": ["casi", "nunca", "siempre", "veces", "menudo"],
              "mal": ["«Bijna» is <b>casi</b>.",
                      "«Bijna altijd» is casi <b>siempre</b> — <i>casi nunca</i> is het omgekeerde."]},
    "opciones": [
      ("Casi siempre como en casa.", True, None),
      ("Casi nunca como en casa.", False,
       "Dat betekent het omgekeerde. «Bijna altijd» is <b>casi siempre</b>."),
    ],
    "acepta": [r"(siempre|normalmente|a\s+veces|a\s+menudo|casi\s+nunca|nunca|casi\s+siempre)",
               r"como\s+en"],
    "pista": "Kies uit: siempre · normalmente · a menudo · a veces · casi nunca.",
    "modelo": "Casi siempre como en casa."},

   {"di": "Y por la tarde, ¿tienes tiempo libre?",
    "nl": "En 's namiddags, heb je vrije tijd?",
    "meta": "Zeg wat je moet doen vóór je vrij bent.",
    "hueco": {"marco": "Primero ___ ___ estudiar, después salgo.",
              "respuestas": [["tengo"], ["que"]],
              "banco": ["tengo", "voy", "que", "de", "a"],
              "mal": ["«Ik moet» begint met <b>tengo</b>.",
                      "De vaste combinatie is <b>tener que</b> + hele werkwoord."]},
    "opciones": [
      ("Primero tengo que estudiar, después salgo.", True, None),
      ("Primero tengo de estudiar, después salgo.", False,
       "Het is <b>tener que</b>, nooit «tener de»."),
      ("Primero voy a estudiar, después salgo.", False,
       "Dat kan, maar dan zeg je een plán. «Ik móét» is <b>tengo que</b>."),
    ],
    "acepta": [r"tengo\s+que\s+\w+"],
    "pista": "«Tengo que + hele werkwoord».",
    "modelo": "Primero tengo que estudiar, después salgo."},

   {"di": "Suena a un día largo. ¿Cómo te sientes al final del día?",
    "nl": "Klinkt als een lange dag. Hoe voel je je op het einde van de dag?",
    "meta": "Zeg hoe je je voelt. Let op: een gevoel is tijdelijk.",
    "hueco": {"marco": "___ bastante ___, pero contento.",
              "respuestas": [["estoy"], ["cansado", "cansada"]],
              "banco": ["estoy", "soy", "cansado", "aburrido", "tranquilo"],
              "mal": ["Een gevoel van dit moment krijgt <b>estar</b>.",
                      "Kies een gevoel: cansado · nervioso · contento · relajado."]},
    "opciones": [
      ("Estoy bastante cansado, pero contento.", True, None),
      ("Soy bastante cansado, pero contento.", False,
       "<i>Ser cansado</i> zou betekenen dat je een vermoeiend persoon bént. "
       "Voor een gevoel: <b>estoy cansado</b>."),
    ],
    "acepta": [r"estoy\s+\w+"],
    "pista": "Gevoelens krijgen <b>estar</b>: «estoy cansado/nervioso/contento».",
    "modelo": "Estoy bastante cansado, pero contento."},
  ],
  "final": "Te entiendo. ¡Yo igual! Bueno, suena el timbre. ¡Hasta luego!",
  "final_nl": "Ik begrijp je. Ik ook! Goed, de bel gaat. Tot straks!",
 },

 # ── U2 · Aquí vivo · huis, buurt, vergelijken ─────────────────────────────
 2: {
  "titulo": "Buscar piso",
  "lugar": "Por teléfono · una habitación en alquiler",
  "tu": "Tú, die een kamer zoekt",
  "otro": "La casera",
  "otro_avatar": "🏠",
  "mision": "Je belt over een kamer. Vraag waar het huis ligt, wat erin staat "
            "en wat er in de buurt is — en vergelijk het met waar je nu woont.",
  "mision_es": "Pregunta por la habitación: dónde está, qué hay y cómo es el barrio.",
  "pasos": [
   {"di": "¿Dígame? Sí, la habitación todavía está libre. ¿Qué quiere saber?",
    "nl": "Hallo? Ja, de kamer is nog vrij. Wat wilt u weten?",
    "meta": "Vraag waar het huis precies ligt.",
    "hueco": {"marco": "¿___ ___ exactamente la casa?",
              "respuestas": [["dónde", "donde"], ["está", "esta"]],
              "banco": ["dónde", "cómo", "está", "es", "hay"],
              "mal": ["«Waar» is <b>dónde</b>, met accent in een vraag.",
                      "De ligging van iets vraag je met <b>está</b>."]},
    "opciones": [
      ("¿Dónde está exactamente la casa?", True, None),
      ("¿Dónde es exactamente la casa?", False,
       "Ligging gaat met <b>estar</b>: «¿dónde está?»"),
    ],
    "acepta": [r"d[oó]nde\s+est[aá]", r"en\s+qu[eé]\s+(calle|barrio)"],
    "pista": "«¿Dónde está …?» of «¿En qué barrio está?»",
    "modelo": "¿Dónde está exactamente la casa?"},

   {"di": "Está en el centro, en una calle tranquila. La habitación es interior.",
    "nl": "In het centrum, in een rustige straat. De kamer geeft uit op de binnenkant.",
    "meta": "Vraag wat er in de kamer staat.",
    "hueco": {"marco": "¿Qué ___ en la ___?",
              "respuestas": [["hay"], ["habitación", "habitacion"]],
              "banco": ["hay", "está", "son", "habitación", "cocina"],
              "mal": ["Om te vragen wát er is: <b>hay</b>.",
                      "Het woord voor kamer is <b>la habitación</b>."]},
    "opciones": [
      ("¿Qué hay en la habitación?", True, None),
      ("¿Qué está en la habitación?", False,
       "<b>Hay</b> vraagt wát er is; <i>está</i> vraagt wáár iets staat."),
    ],
    "acepta": [r"qu[eé]\s+hay", r"hay\s+\w+"],
    "pista": "«¿Qué hay en …?» — met <i>hay</i>, niet met <i>está</i>.",
    "modelo": "¿Qué hay en la habitación?"},

   {"di": "Hay una cama, un armario grande y una mesa debajo de la ventana.",
    "nl": "Er is een bed, een grote kast en een tafel onder het raam.",
    "meta": "Vraag of er een winkel dicht in de buurt is.",
    "hueco": {"marco": "¿Hay un supermercado ___ ___ la casa?",
              "respuestas": [["cerca"], ["de"]],
              "banco": ["cerca", "lejos", "de", "a", "en"],
              "mal": ["«Dichtbij» is <b>cerca</b>.",
                      "De uitdrukking is <b>cerca de</b>."]},
    "opciones": [
      ("¿Hay un supermercado cerca de la casa?", True, None),
      ("¿Hay un supermercado cerca la casa?", False,
       "Er hoort een <b>de</b> bij: «cerca <i>de</i> la casa»."),
    ],
    "acepta": [r"(cerca|lejos|al\s+lado|enfrente)\s*(de)?", r"hay\s+un"],
    "pista": "«¿Hay … cerca de …?» — let op het kleine woordje <i>de</i>.",
    "modelo": "¿Hay un supermercado cerca de la casa?"},

   {"di": "Sí, a dos calles. ¿Y usted dónde vive ahora?",
    "nl": "Ja, twee straten verder. En waar woont u nu?",
    "meta": "Vergelijk: je woont nu in een dorp, dat is rustiger dan de stad.",
    "hueco": {"marco": "En un pueblo. Es ___ tranquilo ___ la ciudad.",
              "respuestas": [["más", "mas"], ["que"]],
              "banco": ["más", "menos", "que", "como", "tan"],
              "mal": ["Een vergelijking begint met <b>más</b> (of <i>menos</i>).",
                      "Na <i>más</i> hoort <b>que</b>: «más … que …»."]},
    "opciones": [
      ("En un pueblo. Es más tranquilo que la ciudad.", True, None),
      ("En un pueblo. Es más tranquilo como la ciudad.", False,
       "De vaste bouw is <b>más … que …</b>. <i>Como</i> hoort bij «tan … como»."),
      ("En un pueblo. Es tan tranquilo que la ciudad.", False,
       "«Tan» hoort bij <b>como</b>: «tan tranquilo como». Met <i>más</i> gebruik "
       "je <b>que</b>."),
    ],
    "acepta": [r"m[aá]s\s+\w+\s+que", r"menos\s+\w+\s+que", r"tan\s+\w+\s+como"],
    "pista": "Drie bouwsels: más … que · menos … que · tan … como.",
    "modelo": "En un pueblo. Es más tranquilo que la ciudad."},

   {"di": "Entiendo. ¿Quiere venir a verla el sábado?",
    "nl": "Ik begrijp het. Wilt u ze zaterdag komen bekijken?",
    "meta": "Zeg ja en vraag hoe laat.",
    "hueco": {"marco": "Sí, ___ gustaría. ¿___ qué hora?",
              "respuestas": [["me"], ["a"]],
              "banco": ["me", "yo", "a", "en", "de"],
              "mal": ["«Ik zou graag» is <b>me gustaría</b>.",
                      "«Hoe laat» is <b>¿a qué hora?</b>"]},
    "opciones": [
      ("Sí, me gustaría. ¿A qué hora?", True, None),
      ("Sí, yo gustaría. ¿A qué hora?", False,
       "Net als <i>me gusta</i>: <b>me gustaría</b>, nooit «yo gustaría»."),
    ],
    "acepta": [r"me\s+gustar[ií]a", r"a\s+qu[eé]\s+hora", r"s[ií]"],
    "pista": "«Me gustaría» + «¿A qué hora?»",
    "modelo": "Sí, me gustaría. ¿A qué hora?"},
  ],
  "final": "A las once. La dirección es calle Mayor, 12. ¡Hasta el sábado!",
  "final_nl": "Om elf uur. Het adres is calle Mayor 12. Tot zaterdag!",
 },

 # ── U3 · Conectados · digitaal + mening ───────────────────────────────────
 3: {
  "titulo": "El debate del móvil",
  "lugar": "En clase · un debate corto",
  "tu": "Tú",
  "otro": "El profesor",
  "otro_avatar": "📱",
  "mision": "Verdedig je mening over gsm's op school: zeg wat je denkt, geef "
            "een reden, en reageer op wat de ander zegt.",
  "mision_es": "Da tu opinión sobre el móvil en clase y responde a otra opinión.",
  "pasos": [
   {"di": "Hoy hablamos del móvil en clase. ¿Qué opinas tú?",
    "nl": "Vandaag praten we over de gsm in de klas. Wat vind jij?",
    "meta": "Geef je mening. Begin met een vaste uitdrukking.",
    "hueco": {"marco": "___ ___ el móvil es útil para estudiar.",
              "respuestas": [["creo"], ["que"]],
              "banco": ["creo", "pienso", "que", "de", "en"],
              "mal": ["Begin met <b>creo</b> of <b>pienso</b>.",
                      "Er hoort altijd <b>que</b> achter: «creo <i>que</i>…»."]},
    "opciones": [
      ("Creo que el móvil es útil para estudiar.", True, None),
      ("Creo el móvil es útil para estudiar.", False,
       "Er ontbreekt <b>que</b>: «creo <i>que</i> el móvil es…»."),
    ],
    "acepta": [r"(creo|pienso|me\s+parece)\s+que", r"en\s+mi\s+opini[oó]n"],
    "pista": "Creo que … · Pienso que … · Me parece que … · En mi opinión, …",
    "modelo": "Creo que el móvil es útil para estudiar."},

   {"di": "Interesante. ¿Y por qué lo dices?",
    "nl": "Interessant. En waarom zeg je dat?",
    "meta": "Geef je reden en voeg er een argument aan toe.",
    "hueco": {"marco": "___ puedes buscar información, y ___ tienes el diccionario.",
              "respuestas": [["porque"], ["además"]],
              "banco": ["porque", "por qué", "además", "sin embargo", "por eso"],
              "mal": ["De reden begint met <b>porque</b>, aan elkaar en zonder accent.",
                      "Een argument erbij zetten doe je met <b>además</b> («bovendien»)."]},
    "opciones": [
      ("Porque puedes buscar información, y además tienes el diccionario.", True, None),
      ("Por qué puedes buscar información, y además tienes el diccionario.", False,
       "<b>Porque</b> aan elkaar is het antwoord; <i>por qué</i> met accent is de vraag."),
      ("Porque puedes buscar información, y sin embargo tienes el diccionario.", False,
       "<i>Sin embargo</i> betekent «toch/echter» en draait je zin om. Je wil "
       "iets tóévoegen: <b>además</b>."),
    ],
    "acepta": [r"porque\s+\w+"],
    "pista": "«Porque …» en dan «además …» om er iets bij te zetten.",
    "modelo": "Porque puedes buscar información, y además tienes el diccionario."},

   {"di": "Nadia dice que el móvil distrae demasiado. ¿Estás de acuerdo con ella?",
    "nl": "Nadia zegt dat de gsm te veel afleidt. Ben je het met haar eens?",
    "meta": "Zeg dat je het niet helemaal eens bent.",
    "hueco": {"marco": "No ___ del todo de ___ con ella.",
              "respuestas": [["estoy"], ["acuerdo"]],
              "banco": ["estoy", "soy", "acuerdo", "razón", "opinión"],
              "mal": ["De uitdrukking is <b>estar de acuerdo</b>, met <i>estar</i>.",
                      "Het woord is <b>acuerdo</b>: «de acuerdo»."]},
    "opciones": [
      ("No estoy del todo de acuerdo con ella.", True, None),
      ("No soy del todo de acuerdo con ella.", False,
       "Het is <b>estar</b> de acuerdo, niet <i>ser</i>."),
    ],
    "acepta": [r"estoy\s+(del\s+todo\s+)?de\s+acuerdo", r"tiene[s]?\s+raz[oó]n"],
    "pista": "«(No) estoy de acuerdo» · «Tienes razón» · «Es verdad, pero…».",
    "modelo": "No estoy del todo de acuerdo con ella."},

   {"di": "Pero reconoce que a veces distrae, ¿no?",
    "nl": "Maar geef toe dat het soms afleidt, niet?",
    "meta": "Geef gedeeltelijk gelijk, maar zet er iets tegenover.",
    "hueco": {"marco": "Es verdad, ___ ___ depende del uso.",
              "respuestas": [["pero"], ["todo", "también"]],
              "banco": ["pero", "y", "todo", "también", "nada"],
              "mal": ["Iets ertegenover zetten doe je met <b>pero</b>.",
                      "De uitdrukking is «todo depende del uso» — of gebruik <i>también</i>."]},
    "opciones": [
      ("Es verdad, pero todo depende del uso.", True, None),
      ("Es verdad, y todo depende del uso.", False,
       "Met <i>y</i> zeg je dat het samengaat. Je wil een tégenwerping: <b>pero</b>."),
    ],
    "acepta": [r"es\s+verdad", r"\bpero\b", r"sin\s+embargo"],
    "pista": "«Es verdad, pero …» of «Por un lado …, por otro lado …».",
    "modelo": "Es verdad, pero todo depende del uso."},

   {"di": "Buen argumento. ¿Y qué propones entonces?",
    "nl": "Goed argument. En wat stel je dan voor?",
    "meta": "Doe een voorstel met een plan-vorm.",
    "hueco": {"marco": "___ ___ solo para trabajar en clase.",
              "respuestas": [["podemos"], ["usarlo"]],
              "banco": ["podemos", "puedo", "usarlo", "usarlos", "usar"],
              "mal": ["Een voorstel voor de klas: <b>podemos</b> («wij kunnen»).",
                      "«Hem gebruiken» is <b>usarlo</b> — het voorwerp plakt achteraan."]},
    "opciones": [
      ("Podemos usarlo solo para trabajar en clase.", True, None),
      ("Puedo usarlo solo para trabajar en clase.", False,
       "Je doet een voorstel voor iedereen: <b>podemos</b> (wij)."),
    ],
    "acepta": [r"podemos\s+\w+", r"(propongo|se\s+puede)"],
    "pista": "«Podemos + hele werkwoord» is een voorstel voor de hele klas.",
    "modelo": "Podemos usarlo solo para trabajar en clase."},
  ],
  "final": "Me parece razonable. Lo probamos una semana y lo hablamos otra vez.",
  "final_nl": "Dat lijkt me redelijk. We proberen het een week en praten er dan opnieuw over.",
 },

 # ── U4 · De viaje · reizen + por/para ─────────────────────────────────────
 4: {
  "titulo": "En la estación",
  "lugar": "Madrid · la estación de Atocha",
  "tu": "Tú, die een kaartje koopt",
  "otro": "El taquillero",
  "otro_avatar": "🚆",
  "mision": "Koop een treinkaartje: bestemming, wanneer, heen en terug — en "
            "zeg waarvoor je gaat.",
  "mision_es": "Compra un billete: destino, día, ida y vuelta, y para qué vas.",
  "pasos": [
   {"di": "Buenos días. ¿Adónde quiere viajar?",
    "nl": "Goedemorgen. Waarheen wilt u reizen?",
    "meta": "Zeg waar je heen wil en dat je met de trein gaat.",
    "hueco": {"marco": "Quiero un billete ___ Sevilla, ___ tren, por favor.",
              "respuestas": [["para", "a"], ["en", "por"]],
              "banco": ["para", "a", "en", "por", "de"],
              "mal": ["De bestemming krijgt <b>para</b> (of <i>a</i>): «un billete para Sevilla».",
                      "Het vervoermiddel krijgt <b>en</b>: «en tren». (<i>Por tren</i> hoor je ook.)"]},
    "opciones": [
      ("Quiero un billete para Sevilla, en tren, por favor.", True, None),
      ("Quiero un billete por Sevilla, en tren, por favor.", False,
       "De bestemming krijgt <b>para</b>: «para Sevilla». <i>Por</i> zou «doorheen» "
       "betekenen."),
    ],
    "acepta": [r"billete\s+(para|a)\s+\w+", r"quiero\s+un\s+billete"],
    "pista": "«Un billete para …» + «en tren» + «por favor».",
    "modelo": "Quiero un billete para Sevilla, en tren, por favor."},

   {"di": "Muy bien. ¿Para qué día?",
    "nl": "Prima. Voor welke dag?",
    "meta": "Zeg voor wanneer, en voor hoe lang je blijft.",
    "hueco": {"marco": "___ el viernes, y me quedo ___ tres días.",
              "respuestas": [["para"], ["por"]],
              "banco": ["para", "por", "en", "a", "de"],
              "mal": ["Een deadline of doeldag krijgt <b>para</b>: «para el viernes».",
                      "Een tíjdsduur krijgt <b>por</b>: «por tres días»."]},
    "opciones": [
      ("Para el viernes, y me quedo por tres días.", True, None),
      ("Por el viernes, y me quedo para tres días.", False,
       "Net omgekeerd: <b>para</b> el viernes (de dag waarvoor) en <b>por</b> "
       "tres días (hoe lang)."),
    ],
    "acepta": [r"para\s+el\s+\w+", r"(el\s+)?(lunes|martes|mi[eé]rcoles|jueves|viernes|s[aá]bado|domingo)"],
    "pista": "<b>Para</b> = de dag waarvoor. <b>Por</b> = hoe lang.",
    "modelo": "Para el viernes, y me quedo por tres días."},

   {"di": "¿Ida y vuelta o solo ida?",
    "nl": "Heen en terug of enkel heen?",
    "meta": "Kies heen en terug.",
    "hueco": {"marco": "___ y ___, por favor.",
              "respuestas": [["ida"], ["vuelta"]],
              "banco": ["ida", "vuelta", "salida", "llegada", "viaje"],
              "mal": ["De heenreis is <b>la ida</b>.",
                      "De terugreis is <b>la vuelta</b>."]},
    "opciones": [
      ("Ida y vuelta, por favor.", True, None),
      ("Salida y llegada, por favor.", False,
       "Dat zijn vertrek en aankomst. Het kaartje heet <b>ida y vuelta</b>."),
    ],
    "acepta": [r"ida\s+y\s+vuelta", r"solo\s+ida"],
    "pista": "De vaste uitdrukking: «ida y vuelta».",
    "modelo": "Ida y vuelta, por favor."},

   {"di": "Son ochenta y dos euros. ¿Y va de vacaciones?",
    "nl": "Dat is tweeëntachtig euro. En gaat u op vakantie?",
    "meta": "Zeg waarvoor je gaat.",
    "hueco": {"marco": "No, voy ___ visitar a mi familia y ___ ver la ciudad.",
              "respuestas": [["para"], ["para"]],
              "banco": ["para", "por", "a", "de", "en"],
              "mal": ["Het doel van iets krijgt <b>para</b> + hele werkwoord.",
                      "Ook hier <b>para</b>: «para ver la ciudad»."]},
    "opciones": [
      ("No, voy para visitar a mi familia y para ver la ciudad.", True, None),
      ("No, voy por visitar a mi familia y por ver la ciudad.", False,
       "Een dóél krijgt <b>para</b> + infinitief. <i>Por</i> gebruik je voor de "
       "oorzaak of de duur."),
    ],
    "acepta": [r"para\s+\w+ar\b", r"para\s+\w+er\b", r"para\s+\w+ir\b", r"voy\s+a\s+\w+"],
    "pista": "Doel = <b>para</b> + hele werkwoord: «para visitar», «para ver».",
    "modelo": "No, voy para visitar a mi familia y para ver la ciudad."},

   {"di": "Perfecto. El tren sale del andén cuatro. ¿Algo más?",
    "nl": "Perfect. De trein vertrekt van perron vier. Nog iets?",
    "meta": "Vraag hoe laat de trein aankomt.",
    "hueco": {"marco": "Sí, ¿___ qué hora ___ el tren a Sevilla?",
              "respuestas": [["a"], ["llega"]],
              "banco": ["a", "en", "llega", "sale", "viene"],
              "mal": ["Een uur krijgt <b>a</b>: «¿a qué hora…?»",
                      "Aankomen is <b>llegar</b>: «llega»."]},
    "opciones": [
      ("Sí, ¿a qué hora llega el tren a Sevilla?", True, None),
      ("Sí, ¿a qué hora sale el tren a Sevilla?", False,
       "<i>Salir</i> is vertrekken. Je wil weten wanneer hij <b>aankomt</b>: llega."),
    ],
    "acepta": [r"a\s+qu[eé]\s+hora", r"(llega|sale)"],
    "pista": "«¿A qué hora llega …?» — <i>llegar</i> is aankomen.",
    "modelo": "Sí, ¿a qué hora llega el tren a Sevilla?"},
  ],
  "final": "A las dos y media de la tarde. ¡Buen viaje!",
  "final_nl": "Om half drie 's middags. Goede reis!",
 },

 # ── U5 · Érase una vez · biografie in het indefinido ──────────────────────
 5: {
  "titulo": "Una vida en cinco frases",
  "lugar": "En la biblioteca · preparando una presentación",
  "tu": "Tú",
  "otro": "La bibliotecaria",
  "otro_avatar": "📖",
  "mision": "Vertel het leven van iemand die je bewondert: geboren, gestudeerd, "
            "wat hij of zij deed, en wanneer. Alles in de verleden tijd.",
  "mision_es": "Cuenta la vida de alguien en pasado: nació, estudió, hizo, ganó.",
  "pasos": [
   {"di": "¿Sobre quién es tu presentación?",
    "nl": "Over wie gaat je presentatie?",
    "meta": "Zeg over wie, en wanneer die geboren is.",
    "hueco": {"marco": "Sobre Frida Kahlo. ___ ___ 1907 en México.",
              "respuestas": [["nació", "nacio"], ["en"]],
              "banco": ["nació", "nace", "nacía", "en", "de"],
              "mal": ["Een afgesloten feit in het verleden: <b>nació</b>.",
                      "Een jaartal krijgt <b>en</b>: «en 1907»."]},
    "opciones": [
      ("Sobre Frida Kahlo. Nació en 1907 en México.", True, None),
      ("Sobre Frida Kahlo. Nace en 1907 en México.", False,
       "Het gebeurde ooit en is voorbij: <b>nació</b>, verleden tijd."),
    ],
    "acepta": [r"naci[oó]", r"en\s+\d{4}"],
    "pista": "«Nació en …» + jaartal.",
    "modelo": "Sobre Frida Kahlo. Nació en 1907 en México."},

   {"di": "¡Qué buena elección! ¿Y qué estudió?",
    "nl": "Wat een goede keuze! En wat studeerde ze?",
    "meta": "Vertel wat ze studeerde en wanneer ze begon te schilderen.",
    "hueco": {"marco": "___ medicina, pero después ___ a pintar.",
              "respuestas": [["estudió", "estudio"], ["empezó", "empezo"]],
              "banco": ["estudió", "estudia", "empezó", "empieza", "empezaba"],
              "mal": ["Verleden tijd: <b>estudió</b>.",
                      "Ook hier een afgesloten feit: <b>empezó</b>."]},
    "opciones": [
      ("Estudió medicina, pero después empezó a pintar.", True, None),
      ("Estudia medicina, pero después empieza a pintar.", False,
       "Het gaat over haar leven, dat voorbij is: <b>estudió</b>, <b>empezó</b>."),
    ],
    "acepta": [r"estudi[oó]", r"empez[oó]"],
    "pista": "Twee vormen op -ó: estudió · empezó · pintó · ganó.",
    "modelo": "Estudió medicina, pero después empezó a pintar."},

   {"di": "¿Y por qué empezó a pintar?",
    "nl": "En waarom begon ze te schilderen?",
    "meta": "Geef de reden: ze had een ongeval.",
    "hueco": {"marco": "___ ___ un accidente muy grave.",
              "respuestas": [["porque"], ["tuvo"]],
              "banco": ["porque", "por qué", "tuvo", "tiene", "tenía"],
              "mal": ["De reden begint met <b>porque</b>.",
                      "<i>Tener</i> is onregelmatig in het verleden: <b>tuvo</b>."]},
    "opciones": [
      ("Porque tuvo un accidente muy grave.", True, None),
      ("Porque tenió un accidente muy grave.", False,
       "<i>Tener</i> is onregelmatig: <b>tuvo</b>, niet «tenió»."),
    ],
    "acepta": [r"porque\s+\w+", r"\btuvo\b"],
    "pista": "De onregelmatige: fue · <b>tuvo</b> · hizo · estuvo · dijo · vino · pudo.",
    "modelo": "Porque tuvo un accidente muy grave."},

   {"di": "Es una historia impresionante. ¿Y qué hizo después?",
    "nl": "Dat is een indrukwekkend verhaal. En wat deed ze daarna?",
    "meta": "Vertel wat ze maakte en wanneer.",
    "hueco": {"marco": "___ muchos autorretratos y ___ famosa en todo el mundo.",
              "respuestas": [["pintó", "pinto", "hizo"], ["fue"]],
              "banco": ["pintó", "pinta", "fue", "era", "es"],
              "mal": ["Verleden tijd: <b>pintó</b> (of <i>hizo</i>).",
                      "«Werd/was» als afgesloten feit: <b>fue</b>."]},
    "opciones": [
      ("Pintó muchos autorretratos y fue famosa en todo el mundo.", True, None),
      ("Pintó muchos autorretratos y es famosa en todo el mundo.", False,
       "Binnen dit verhaal blijf je in het verleden: <b>fue</b> famosa."),
    ],
    "acepta": [r"(pint[oó]|hizo|escribi[oó]|gan[oó]|cre[oó])", r"\bfue\b"],
    "pista": "Werkwoorden op -ó, en het onregelmatige <b>fue</b>.",
    "modelo": "Pintó muchos autorretratos y fue famosa en todo el mundo."},

   {"di": "¿Cuándo murió?",
    "nl": "Wanneer is ze gestorven?",
    "meta": "Zeg wanneer, met een tijdsbepaling uit het verleden.",
    "hueco": {"marco": "___ en 1954, ___ setenta años.",
              "respuestas": [["murió", "murio"], ["hace"]],
              "banco": ["murió", "muere", "hace", "desde", "en"],
              "mal": ["Verleden tijd van <i>morir</i>: <b>murió</b>.",
                      "«… jaar geleden» is <b>hace</b> + aantal jaren."]},
    "opciones": [
      ("Murió en 1954, hace setenta años.", True, None),
      ("Murió en 1954, desde setenta años.", False,
       "«Zeventig jaar geleden» is <b>hace</b> setenta años."),
    ],
    "acepta": [r"muri[oó]", r"en\s+\d{4}"],
    "pista": "«Murió en …» + jaartal. «… geleden» = <b>hace</b> + jaren.",
    "modelo": "Murió en 1954, hace setenta años."},
  ],
  "final": "Con eso tienes una presentación estupenda. ¡Mucha suerte mañana!",
  "final_nl": "Daarmee heb je een prima presentatie. Veel succes morgen!",
 },

 # ── U6 · Cuando era pequeño · imperfecto + vergelijken ────────────────────
 6: {
  "titulo": "Cuando éramos pequeños",
  "lugar": "En casa de la abuela · mirando fotos viejas",
  "tu": "Tú",
  "otro": "La abuela",
  "otro_avatar": "👵",
  "mision": "Vertel hoe het vroeger was: wat je deed, waar je woonde, hoe het "
            "eruitzag — en vergelijk het met nu.",
  "mision_es": "Cuenta cómo era tu vida de pequeño y compárala con ahora.",
  "pasos": [
   {"di": "Mira esta foto. ¿Cómo eras tú de pequeño?",
    "nl": "Kijk naar deze foto. Hoe was jij als kind?",
    "meta": "Beschrijf hoe je was. Gebruik de vorm voor «vroeger».",
    "hueco": {"marco": "___ muy tímido y ___ el pelo largo.",
              "respuestas": [["era"], ["tenía", "tenia"]],
              "banco": ["era", "fui", "soy", "tenía", "tuve"],
              "mal": ["Hoe iets vróéger wás: <b>era</b>.",
                      "Ook een beschrijving: <b>tenía</b>."]},
    "opciones": [
      ("Era muy tímido y tenía el pelo largo.", True, None),
      ("Fui muy tímido y tuve el pelo largo.", False,
       "<i>Fui</i> en <i>tuve</i> zijn voor iets dat één keer gebeurde. Voor hoe "
       "het gewóón was: <b>era</b>, <b>tenía</b>."),
    ],
    "acepta": [r"\bera\b", r"\ten[ií]a\b", r"\bten[ií]a\b"],
    "pista": "De vormen voor «vroeger»: era · tenía · vivía · iba · jugaba.",
    "modelo": "Era muy tímido y tenía el pelo largo."},

   {"di": "¡Igual que tu madre! ¿Y dónde vivíais entonces?",
    "nl": "Net als je moeder! En waar woonden jullie toen?",
    "meta": "Zeg waar je woonde en wat je daar deed.",
    "hueco": {"marco": "___ en un pueblo pequeño y ___ en la calle todo el día.",
              "respuestas": [["vivía", "vivia"], ["jugaba"]],
              "banco": ["vivía", "viví", "jugaba", "jugué", "juego"],
              "mal": ["Iets dat jarenlang zo was: <b>vivía</b>.",
                      "Een gewoonte van vroeger: <b>jugaba</b>."]},
    "opciones": [
      ("Vivía en un pueblo pequeño y jugaba en la calle todo el día.", True, None),
      ("Viví en un pueblo pequeño y jugué en la calle todo el día.", False,
       "Voor een gewóónte van vroeger: <b>vivía</b> en <b>jugaba</b>."),
    ],
    "acepta": [r"viv[ií]a", r"jugaba", r"iba", r"ve[ií]a"],
    "pista": "Gewoontes van vroeger eindigen op -aba of -ía: jugaba · vivía · iba.",
    "modelo": "Vivía en un pueblo pequeño y jugaba en la calle todo el día."},

   {"di": "Sí, antes los niños jugaban fuera. ¿Y ahora?",
    "nl": "Ja, vroeger speelden de kinderen buiten. En nu?",
    "meta": "Zet vroeger tegenover nu.",
    "hueco": {"marco": "___ jugaba fuera, pero ___ estoy más en casa.",
              "respuestas": [["antes"], ["ahora"]],
              "banco": ["antes", "después", "ahora", "ya", "siempre"],
              "mal": ["«Vroeger» is <b>antes</b>.",
                      "«Nu» is <b>ahora</b>."]},
    "opciones": [
      ("Antes jugaba fuera, pero ahora estoy más en casa.", True, None),
      ("Después jugaba fuera, pero ahora estoy más en casa.", False,
       "«Vroeger» is <b>antes</b>. <i>Después</i> betekent «daarna»."),
    ],
    "acepta": [r"\bantes\b", r"\bahora\b", r"ya\s+no"],
    "pista": "Het vaste paar: <b>antes</b> … pero <b>ahora</b> …",
    "modelo": "Antes jugaba fuera, pero ahora estoy más en casa."},

   {"di": "¿Y qué era mejor, entonces o ahora?",
    "nl": "En wat was beter, toen of nu?",
    "meta": "Vergelijk de twee met een vergelijkende vorm.",
    "hueco": {"marco": "Creo que antes teníamos ___ libertad ___ ahora.",
              "respuestas": [["más", "mas"], ["que"]],
              "banco": ["más", "menos", "que", "como", "tan"],
              "mal": ["Een vergelijking begint met <b>más</b> of <b>menos</b>.",
                      "Na <i>más</i> hoort <b>que</b>."]},
    "opciones": [
      ("Creo que antes teníamos más libertad que ahora.", True, None),
      ("Creo que antes teníamos más libertad como ahora.", False,
       "Bij <i>más</i> hoort <b>que</b>. <i>Como</i> hoort bij «tan … como»."),
      ("Creo que antes teníamos tan libertad que ahora.", False,
       "«Tan» werkt met <b>como</b>: «tan … como». Met <i>más</i> gebruik je <b>que</b>."),
    ],
    "acepta": [r"m[aá]s\s+\w+\s+que", r"menos\s+\w+\s+que", r"mejor\s+que", r"peor\s+que"],
    "pista": "más … que · menos … que · mejor que · peor que.",
    "modelo": "Creo que antes teníamos más libertad que ahora."},

   {"di": "Puede ser. ¿Qué es lo que más recuerdas de tu infancia?",
    "nl": "Dat kan. Wat herinner je je het meest van je kindertijd?",
    "meta": "Vertel één herinnering: wat je elke zomer deed.",
    "hueco": {"marco": "Todos los veranos ___ a casa de mis abuelos y ___ en el río.",
              "respuestas": [["iba"], ["nadaba", "jugaba"]],
              "banco": ["iba", "fui", "voy", "nadaba", "nadé"],
              "mal": ["Elke zomer opnieuw → <b>iba</b>.",
                      "Ook een gewoonte: <b>nadaba</b> (of <i>jugaba</i>)."]},
    "opciones": [
      ("Todos los veranos iba a casa de mis abuelos y nadaba en el río.", True, None),
      ("Todos los veranos fui a casa de mis abuelos y nadé en el río.", False,
       "Iets wat élke zomer gebeurde, krijgt <b>iba</b> en <b>nadaba</b>."),
    ],
    "acepta": [r"\biba\b", r"(nadaba|jugaba|com[ií]a|ve[ií]a|pasaba)"],
    "pista": "«Todos los veranos …» vraagt de vorm voor gewoontes: iba · nadaba.",
    "modelo": "Todos los veranos iba a casa de mis abuelos y nadaba en el río."},
  ],
  "final": "Qué recuerdos… Anda, quédate a merendar y me cuentas más.",
  "final_nl": "Wat een herinneringen… Kom, blijf een vieruurtje eten en vertel me meer.",
 },

 # ── U7 · ¡Opina y cuídate! · gezondheid, milieu, imperativo ───────────────
 7: {
  "titulo": "El consejo",
  "lugar": "En el centro de salud del instituto",
  "tu": "Tú",
  "otro": "La enfermera",
  "otro_avatar": "🩺",
  "mision": "Vertel wat er scheelt, luister naar de raad, en geef zelf raad "
            "aan een vriend. Gebruik de gebiedende wijs.",
  "mision_es": "Cuenta cómo estás, recibe consejos y da tú un consejo.",
  "pasos": [
   {"di": "Hola, ¿qué te pasa?",
    "nl": "Hallo, wat scheelt er?",
    "meta": "Zeg dat je moe bent en slecht slaapt.",
    "hueco": {"marco": "___ muy cansado y ___ duermo bien.",
              "respuestas": [["estoy"], ["no"]],
              "banco": ["estoy", "soy", "no", "sí", "nunca"],
              "mal": ["Hoe je je nú voelt: <b>estoy</b>.",
                      "De ontkenning staat vóór het werkwoord: <b>no</b> duermo."]},
    "opciones": [
      ("Estoy muy cansado y no duermo bien.", True, None),
      ("Soy muy cansado y no duermo bien.", False,
       "Een toestand van dit moment: <b>estoy cansado</b>."),
    ],
    "acepta": [r"estoy\s+\w+", r"no\s+duermo"],
    "pista": "«Estoy + gevoel» en «no duermo bien».",
    "modelo": "Estoy muy cansado y no duermo bien."},

   {"di": "¿Y cuántas horas duermes al día?",
    "nl": "En hoeveel uur slaap je per dag?",
    "meta": "Zeg hoeveel, en geef de reden.",
    "hueco": {"marco": "Unas cinco ___, ___ estudio hasta muy tarde.",
              "respuestas": [["horas"], ["porque"]],
              "banco": ["horas", "años", "porque", "por eso", "además"],
              "mal": ["Het woord is <b>horas</b> — uren.",
                      "De reden begint met <b>porque</b>, niet met <i>por eso</i>."]},
    "opciones": [
      ("Unas cinco horas, porque estudio hasta muy tarde.", True, None),
      ("Unas cinco horas, por eso estudio hasta muy tarde.", False,
       "<i>Por eso</i> betekent «daarom» en draait oorzaak en gevolg om. "
       "De reden geef je met <b>porque</b>."),
    ],
    "acepta": [r"porque\s+\w+", r"\bhoras\b"],
    "pista": "«… porque …» — de reden, niet het gevolg.",
    "modelo": "Unas cinco horas, porque estudio hasta muy tarde."},

   {"di": "Eso es poco. Te aconsejo: duerme ocho horas y haz algo de deporte.",
    "nl": "Dat is weinig. Mijn raad: slaap acht uur en doe wat sport.",
    "meta": "Vraag haar nog een concrete raad.",
    "hueco": {"marco": "¿Qué ___ hacer ___ dormir mejor?",
              "respuestas": [["puedo"], ["para"]],
              "banco": ["puedo", "puedes", "para", "por", "que"],
              "mal": ["Bij <i>yo</i>: <b>puedo</b>.",
                      "Een doel krijgt <b>para</b> + hele werkwoord."]},
    "opciones": [
      ("¿Qué puedo hacer para dormir mejor?", True, None),
      ("¿Qué puedo hacer por dormir mejor?", False,
       "Een doel krijgt <b>para</b>: «para dormir mejor»."),
    ],
    "acepta": [r"qu[eé]\s+puedo\s+hacer", r"para\s+\w+"],
    "pista": "«¿Qué puedo hacer para …?»",
    "modelo": "¿Qué puedo hacer para dormir mejor?"},

   {"di": "Apaga el móvil una hora antes y bebe menos café por la tarde.",
    "nl": "Zet je gsm een uur op voorhand uit en drink 's namiddags minder koffie.",
    "meta": "Je vriend heeft hetzelfde probleem. Geef hém die raad — met de gebiedende wijs.",
    "hueco": {"marco": "___ el móvil y ___ agua en vez de café.",
              "respuestas": [["apaga"], ["bebe"]],
              "banco": ["apaga", "apagar", "apagas", "bebe", "beber"],
              "mal": ["De gebiedende wijs van <i>apagar</i> tegen <i>tú</i>: <b>apaga</b>.",
                      "En van <i>beber</i>: <b>bebe</b>."]},
    "opciones": [
      ("Apaga el móvil y bebe agua en vez de café.", True, None),
      ("Apagar el móvil y beber agua en vez de café.", False,
       "Een raad geef je met de gebiedende wijs: <b>apaga</b>, <b>bebe</b> — niet "
       "met het hele werkwoord."),
      ("Apagas el móvil y bebes agua en vez de café.", False,
       "Dat is een mededeling. Als raad: <b>apaga</b> en <b>bebe</b>."),
    ],
    "acepta": [r"\bapaga\b", r"\bbebe\b", r"\b(come|haz|cuida|duerme|recicla)\b"],
    "pista": "De gebiedende wijs tegen <i>tú</i>: apaga · bebe · come · haz · duerme.",
    "modelo": "Apaga el móvil y bebe agua en vez de café."},

   {"di": "¡Muy bien explicado! ¿Y tú qué opinas: dormimos poco los jóvenes?",
    "nl": "Heel goed uitgelegd! En wat vind jij: slapen jongeren te weinig?",
    "meta": "Geef je mening met een reden.",
    "hueco": {"marco": "___ que sí, ___ pasamos mucho tiempo con la pantalla.",
              "respuestas": [["creo", "pienso"], ["porque"]],
              "banco": ["creo", "pienso", "porque", "además", "sin embargo"],
              "mal": ["Begin met <b>creo</b> of <b>pienso</b>.",
                      "De reden krijgt <b>porque</b>."]},
    "opciones": [
      ("Creo que sí, porque pasamos mucho tiempo con la pantalla.", True, None),
      ("Creo que sí, sin embargo pasamos mucho tiempo con la pantalla.", False,
       "<i>Sin embargo</i> zet iets tegenóver je mening. Voor de reden: <b>porque</b>."),
    ],
    "acepta": [r"(creo|pienso|me\s+parece)\s+que", r"en\s+mi\s+opini[oó]n"],
    "pista": "«Creo que … porque …»",
    "modelo": "Creo que sí, porque pasamos mucho tiempo con la pantalla."},
  ],
  "final": "Estoy de acuerdo contigo. Prueba una semana y vuelve a contármelo.",
  "final_nl": "Ik ben het met je eens. Probeer het een week en kom het me vertellen.",
 },
}
